'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const nodes=[{id:'base',name:'본부 / NEREID',x:270,y:510,type:'본부',detail:'연산코어 · 충전 · 군수 지휘',stock:'2,480',power:'420 / 600 kW'},{id:'refinery',name:'제1 가공거점',x:575,y:490,type:'가공',detail:'원광 정제 → 전장품 제조',stock:'380 / 800',power:'90 / 120 kW'},{id:'iron',name:'N-014 / 철광층',x:365,y:335,type:'철',purity:50,rate:60,stock:'320 / 600',power:'유선 연결',detail:'근거리 철광층 · 채굴모함 전개'},{id:'copper',name:'N-027 / 구리광층',x:700,y:330,type:'구리',purity:80,rate:50,stock:'120 / 400',power:'배터리 72%',detail:'원거리 고순도 광층 · 운송 필요'},{id:'gas',name:'N-031 / 가스 분출구',x:540,y:630,type:'가스',purity:65,rate:30,stock:'0 / 300',power:'연결 없음',detail:'설비 미전개 · 탐지 완료'}];
const state={selected:'base',tool:'select',time:0,paused:false,speed:1,scan:null,discovered:false,orders:[],draft:[],view:{x:0,y:0,w:1000,h:760},quest:{inspect:false,scan:false,route:false},log:[]};
const tools=[['select','↖','선택','해역의 대상을 선택해 상태를 확인하세요.'],['pan','✥','이동','해역을 드래그해 이동합니다. 휠로 확대할 수 있습니다.'],['scan','⌖','탐사','해역에서 조사 영역을 드래그하세요. 탐사 진행에는 12초가 걸립니다.'],['dispatch','➤','출정','목표를 선택하고 우측에서 출정 목적과 편성을 확인하세요.'],['route','⌁','정기항로','거점을 순서대로 클릭한 뒤 우측에서 항로를 등록하세요.'],['build','⊞','시설 개발','개발할 노드를 선택하세요. 건설은 상세 MVP에서 연결됩니다.'],['recover','↶','보급·회수','대상을 선택해 보급과 회수 조건을 확인하세요.'],['core','▦','관제 할당','코어 슬롯과 현재 작전 목록을 확인하세요.']];
const panels={missions:'임무 / MAIN QUEST',power:'전력망',resources:'자원·가공',fleet:'함대·방어',research:'연구',people:'인력·교역',cores:'연산코어',notes:'계산 메모'};
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function toast(s){$('#toast').textContent=s;$('#toast').classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>$('#toast').classList.remove('show'),3000);}
function stamp(){return new Date((8*3600+state.time)*1000).toISOString().slice(11,19);}
function log(s,type='SYSTEM'){state.log.unshift({time:stamp(),s,type});state.log=state.log.slice(0,60);$('#logs').innerHTML=state.log.map(l=>'<div class="logrow"><time>'+l.time+'</time><span class="tag">'+l.type+'</span><span>'+esc(l.s)+'</span></div>').join('');}
function graph(color='#9abd9f'){return '<svg class="miniGraph" viewBox="0 0 240 68"><path d="M0 16H240M0 38H240M0 60H240" stroke="#ffffff0c"/><path d="M0 53L15 49L25 51L38 35L55 39L68 28L83 29L98 18L110 24L126 21L139 31L158 27L172 19L190 22L205 14L221 20L240 17" fill="none" stroke="'+color+'" stroke-width="1.5"/></svg>';}
function renderNodes(){ $('#nodeLayer').innerHTML=nodes.map(n=>'<g class="mapnode" data-id="'+n.id+'" transform="translate('+n.x+' '+n.y+')"><circle class="halo" r="31" fill="#a1c6a810" stroke="#a1c6a855" opacity="'+(state.selected===n.id?1:0)+'"/>'+(n.id==='base'?'<circle r="11" fill="#93b7a0"/><path d="M-5 0H5M0-5V5" stroke="#17322c" stroke-width="2"/>':n.id==='refinery'?'<rect x="-8" y="-8" width="16" height="16" fill="#1d373b" stroke="#c1b488"/>':'<path d="M0-9L9 0L0 9L-9 0Z" fill="#1c3337" stroke="#8ab6b6"/>')+'<text class="label" x="18" y="-4">'+esc(n.name)+'</text><text class="sub" x="18" y="13">'+esc(n.type==='본부'?'':n.id==='base'?'COMMAND / ONLINE':n.purity?'PURITY '+n.purity+'% · '+n.rate+' / min':'PROCESSING / STANDBY')+'</text></g>').join('')+'<g transform="translate(840 195)"><path d="M0-12L12 10H-12Z" fill="#d8877910" stroke="#ce8479"/><text x="20" y="0" class="label" style="fill:#cb9187">CONTACT / 미식별</text><text x="20" y="17" class="sub">위협 예시 · 08:40</text></g>';
$('#nodeList').innerHTML=nodes.filter(n=>n.purity).map(n=>'<button class="treeitem '+(state.selected===n.id?'selected':'')+'" data-node="'+n.id+'">◇ <span>'+esc(n.name)+'<small>'+esc(n.type)+' · 순도 '+n.purity+'%</small></span></button>').join('');$('#nodeCount').textContent=String(nodes.filter(n=>n.purity).length).padStart(2,'0');applySearch();}
function select(id){state.selected=id;state.quest.inspect=true;renderNodes();renderInspector();updateQuests();}
function renderInspector(){let n=nodes.find(n=>n.id===state.selected);let content='<div class="inspectcontent"><div class="eyebrow">'+esc(n.type)+' / '+esc(n.id.toUpperCase())+'</div><h1>'+esc(n.name)+'</h1><div class="inspectdesc">'+esc(n.detail)+'</div><div class="stat">전력 공급 <b>'+esc(n.power)+'</b></div><div class="stat">현장 재고 <b>'+esc(n.stock)+'</b></div>'+(n.purity?'<div class="stat">순도 <b>'+n.purity+'%</b></div><div class="stat">채굴률 예시 <b>'+n.rate+' / min</b></div>':'<div class="stat">연결 상태 <b>ONLINE</b></div>')+graph()+'<div class="caption"><span>SUPPLY TREND / 예시</span><span>최근 30분</span></div>';
if(state.tool==='route'){content+='<h2>정기항로 초안</h2><p class="muted small">지도에서 두 곳 이상의 거점을 지정하세요.</p>'+state.draft.map((id,i)=>'<div class="routepoint">'+(i+1)+'. '+esc(nodes.find(n=>n.id===id).name)+'</div>').join('')+'<label>운송 편성<select id="cargo"><option value="200">수송선 1척 · 200 화물</option><option value="400">수송선 2척 · 400 화물</option></select></label><button id="commitRoute" class="primary" '+(state.draft.length<2?'disabled':'')+'>반복항로 등록 · 코어 1</button>';}
else if(state.tool==='dispatch'){content+='<h2>출정 명령</h2><select id="missionType"><option>방어선 구축</option><option>공격 진출</option><option>채굴선 출정</option></select><p class="muted small">기초 명령 등록만 지원합니다. 이동·교전·채굴은 아직 연결되지 않았습니다.</p><button id="dispatchOrder" class="primary">작전 등록 · 코어 1</button>';}
else if(state.tool==='build'||state.tool==='recover'){content+='<h2>'+ (state.tool==='build'?'시설 개발':'보급·회수')+'</h2><p class="muted">상세 기능 준비 중입니다. 시설·함대 패널에서 계획된 항목을 확인할 수 있습니다.</p><button class="primary" data-panel="'+(state.tool==='build'?'resources':'fleet')+'">관련 목록 열기</button>';}
else content+='<button class="primary" data-panel="'+(n.id==='base'?'power':'resources')+'">상세 정보 창 열기 ↗</button>';
$('#inspectorBody').innerHTML=content+'</div>';$('#commitRoute')?.addEventListener('click',commitRoute);$('#dispatchOrder')?.addEventListener('click',()=>{let mode=$('#missionType').value;if(addOrder(mode+' / '+n.name)){log(mode+' 초안 등록: '+n.name,'ORDER');toast('명령이 등록되었습니다. 실제 작전 시뮬레이션은 준비 중입니다.');}});}
function setTool(id){state.tool=id;let t=tools.find(t=>t[0]===id);$('#toolName').textContent=t[2];$('#toolHint').textContent=t[3];$$('.toolbar button').forEach(b=>{b.classList.toggle('active',b.dataset.tool===id);b.setAttribute('aria-pressed',b.dataset.tool===id);});$('#clearDraft').hidden=id!=='route';$('#map').style.cursor=id==='pan'?'grab':id==='scan'?'crosshair':'default';renderInspector();if(id==='core')openPanel('cores');}
function updateQuests(){const q=state.quest, done=Object.values(q).filter(Boolean).length;$('#questBar').style.width=done/3*100+'%';$('#questSummary').innerHTML=[['inspect','거점 상태 확인'],['scan','새 해역 탐사 완료'],['route','정기항로 등록']].map(([k,t])=>'<div>'+(q[k]?'✓':'○')+' '+t+'</div>').join('');let w=$('#window-missions .windowbody');if(w)w.innerHTML=panelHTML('missions');if(done===3&&!updateQuests.complete){updateQuests.complete=true;log('메인퀘스트 01 완료. 드래프트 체험 목표를 모두 달성했습니다.','MISSION');toast('임무 완료 · 다시 연결되는 해역');}}
function addOrder(name){if(state.orders.length+(state.scan?1:0)>=4){toast('연산코어가 모두 사용 중입니다. 활성 명령을 종료하세요.');return false;}state.orders.push({id:Date.now()+Math.random(),name});renderOrders();return true;}
function renderOrders(){let used=state.orders.length+(state.scan?1:0);$('#coreLabel').textContent=used+' / 4';$('#orderCount').textContent=String(used).padStart(2,'0');$('#orders').innerHTML=(state.scan?'<div class="treeitem">⌖ 탐사 실행 중</div>':'')+state.orders.map(o=>'<div class="treeitem"><span>'+esc(o.name)+'</span><button data-cancel="'+o.id+'" title="명령 종료">×</button></div>').join('')||( '<p class="muted padded">등록된 명령이 없습니다.</p>');let w=$('#window-cores .windowbody');if(w)w.innerHTML=panelHTML('cores');}
function commitRoute(){if(state.draft.length<2)return;let capacity=Number($('#cargo').value),path=[...state.draft];if(!addOrder('정기항로 '+path.map(id=>nodes.find(n=>n.id===id).name.split(' / ')[0]).join(' → ')))return;let points=path.map(id=>{let n=nodes.find(n=>n.id===id);return n.x+','+n.y;});points.push(points[0]);const line=document.createElementNS('http://www.w3.org/2000/svg','polyline');line.setAttribute('points',points.join(' '));line.setAttribute('fill','none');line.setAttribute('stroke','#b6c4a4');line.setAttribute('stroke-width','2');line.setAttribute('stroke-dasharray','7 6');line.dataset.order=state.orders.at(-1).id;$('#routeLayer').append(line);state.quest.route=true;log('반복항로 등록 / '+capacity+' 화물 · 실제 운송은 MVP 예정','ROUTE');state.draft=[];renderDraft();renderInspector();updateQuests();toast('항로가 등록되었습니다.');}
function renderDraft(){let old=$('#draftLine');if(old)old.remove();if(!state.draft.length)return;let line=document.createElementNS('http://www.w3.org/2000/svg','polyline');line.id='draftLine';line.setAttribute('points',state.draft.map(id=>{let n=nodes.find(n=>n.id===id);return n.x+','+n.y;}).join(' '));line.setAttribute('fill','none');line.setAttribute('stroke','#d2bb7e');line.setAttribute('stroke-width','2');line.setAttribute('stroke-dasharray','3 5');$('#routeLayer').append(line);}
function table(head,rows){return '<table><thead><tr>'+head.map(h=>'<th>'+h+'</th>').join('')+'</tr></thead><tbody>'+rows.map(r=>'<tr>'+r.map(c=>'<td>'+c+'</td>').join('')+'</tr>').join('')+'</tbody></table>';}
function panelHTML(id){const demo='<p>설계 예시입니다. 생산·소비·전투 및 거래는 아직 시뮬레이션하지 않습니다.</p>';switch(id){
case'missions':return '<span class="badge">MAIN QUEST / CHAPTER 01</span><h2>다시 연결되는 해역</h2><p>관제 시스템을 재가동했습니다. 탐사선으로 주변 해역을 조사하고 첫 보급 항로를 등록하십시오.</p>'+[['inspect','거점 상태 확인','지도 또는 좌측 목록에서 대상을 선택합니다.'],['scan','주변 해역 탐사','⌖ 탐사 도구로 해역을 드래그하고 완료를 기다립니다.'],['route','첫 정기항로 등록','⌁ 항로 도구로 두 거점을 클릭하고 등록합니다.']].map(([k,t,h])=>'<div class="queststep '+(state.quest[k]?'done':'')+'">'+(state.quest[k]?'✓':'○')+' '+t+'<small>'+h+'</small></div>').join('')+'<p>후속 임무: 전력 공급 → 가공시설 가동 → 첫 방어 → 출정.<br>후속 임무와 보상은 MVP에서 연결됩니다.</p>';
case'power':return '<span class="badge">LOCAL GRID / 예시</span><h2>본부 전력망</h2>'+graph()+table(['거점','공급 방식','상태'],[['본부','태양광 · 풍력','420 / 600 kW'],['N-014','유선 송전','연결'],['N-027','배터리 정기선','72%'],['가공거점','자체 발전','90 / 120 kW']])+'<p>향후: 생산·소비 비교, 배터리 잔량, 다음 입항과 예상 소진시각.</p>'+demo;
case'resources':return table(['원료','용도','재고 예시'],[['철','구조재 · 선체','2,480'],['구리','도체 · 전장품','860'],['금','고급 시설 · 코어','24'],['가스','함선 연료','1,200'],['석영','레이더 · 연산','340'],['축전 소재','배터리 팩','80']])+'<p>원광 → 정제 → 물품 → 기지 입고<br>순도 × 회수율과 공정별 처리량으로 생산 계산.</p>'+demo;
case'fleet':return table(['함종','역할','보유'],[['경비정','호위 · 방어','3'],['순양함','주력 전투','1'],['수송선','정기 · 원정 운송','2'],['탐사선','탐사 · 식별','1'],['채굴모함','전개 · 회수','1'],['지원선','인력 · 아티펙트','미해금']])+'<h2>고정 방어 / 정박지</h2><p>기본 포대 · 레이더 · 함선 정박 슬롯<br>적 접촉 표시는 화면 예시이며 실제 공격은 발생하지 않습니다.</p>'+demo;
case'research':return table(['분야','첫 연구','상태'],[['추출·정제','회수율 개선','계획'],['관제','연산코어 증설','계획'],['군수','순양함 설계','계획'],['전력','고밀도 배터리','계획']])+demo;
case'people':return table(['전문가','역할','배치 예시'],[['윤서 / 기관사','전력 · 정비','본부'],['이안 / 항해사','운송 · 항로','본부'],['하린 / 연구원','연구 · 분석','본부']])+'<h2>교역 통신</h2><p>구조재·회수품으로 금과 생활보급품을 확보하는 공간입니다. 인명은 임시 예시입니다.</p>'+demo;
case'cores':return '<span class="badge">COMMAND CAPACITY</span><h2>'+ (state.orders.length+(state.scan?1:0))+' / 4 코어 사용 중</h2><p>탐사 실행과 등록한 작전마다 코어 1개를 사용합니다. 탐사 완료 시 슬롯이 반환됩니다.</p>'+state.orders.map(o=>'<div class="stat"><span>'+esc(o.name)+'</span><button data-cancel="'+o.id+'">종료</button></div>').join('')+'<p>등급별 가속과 실제 자원 비용은 이후 연결됩니다.</p>';
case'notes':return '<span class="badge">OPERATOR NOTES</span><p>직접 계산한 생산 계획을 기록하세요. 배치 저장 시 함께 보관됩니다.</p><textarea id="noteText" aria-label="계산 메모">'+esc(state.note||'30 × 0.80 × 0.90 = 21.6 / min\n운송 증설 후: 50 × 0.80 × 0.90 = 36 / min')+'</textarea>';
}}
let topZ=20;
function openPanel(id,layout){if(!panels[id])return;let existing=$('#window-'+id);if(existing){existing.style.zIndex=++topZ;return;}let w=document.createElement('section');w.className='floating';w.id='window-'+id;w.setAttribute('aria-label',panels[id]);w.innerHTML='<div class="paneltitle"><span>'+panels[id]+'</span><button aria-label="'+panels[id]+' 닫기">×</button></div><div class="windowbody">'+panelHTML(id)+'</div>';$('#floatingLayer').append(w);let count=$$('.floating').length;Object.assign(w.style,{left:Math.min(250+count*20,innerWidth-300)+'px',top:Math.min(130+count*20,innerHeight-200)+'px',zIndex:++topZ});if(layout){w.style.left=Math.max(0,Math.min(layout.x,innerWidth-100))+'px';w.style.top=Math.max(0,Math.min(layout.y,innerHeight-40))+'px';w.style.width=Math.min(layout.w,innerWidth-20)+'px';w.style.height=Math.min(layout.h,innerHeight-70)+'px';}w.querySelector('.paneltitle button').onclick=()=>w.remove();w.addEventListener('pointerdown',()=>w.style.zIndex=++topZ);let drag;const title=w.querySelector('.paneltitle');title.addEventListener('pointerdown',e=>{if(e.target.closest('button'))return;drag={x:e.clientX,y:e.clientY,left:w.offsetLeft,top:w.offsetTop};title.setPointerCapture(e.pointerId);});title.addEventListener('pointermove',e=>{if(!drag)return;w.style.left=Math.max(0,Math.min(innerWidth-100,drag.left+e.clientX-drag.x))+'px';w.style.top=Math.max(54,Math.min(innerHeight-40,drag.top+e.clientY-drag.y))+'px';});title.addEventListener('pointerup',()=>drag=null);$('#panelPicker').hidden=true;}
$('#panelPicker').innerHTML=Object.entries(panels).map(([k,v])=>'<button data-panel="'+k+'">＋ '+v+'</button>').join('');
$('.toolbar').innerHTML=tools.map(t=>'<button data-tool="'+t[0]+'" title="'+t[2]+'" aria-label="'+t[2]+'">'+t[1]+'</button>').join('');
document.addEventListener('click',e=>{let b=e.target.closest('[data-panel]');if(b)openPanel(b.dataset.panel);b=e.target.closest('[data-node]');if(b)select(b.dataset.node);b=e.target.closest('[data-tool]');if(b)setTool(b.dataset.tool);b=e.target.closest('[data-cancel]');if(b){state.orders=state.orders.filter(o=>String(o.id)!==b.dataset.cancel);$$('[data-order]').filter(l=>l.dataset.order===b.dataset.cancel).forEach(l=>l.remove());renderOrders();log('명령 종료 / 코어 반환','ORDER');}});
document.addEventListener('input',e=>{if(e.target.id==='noteText')state.note=e.target.value;});
$('#windowMenu').onclick=()=>$('#panelPicker').hidden=!$('#panelPicker').hidden;
$('#clearDraft').onclick=()=>{state.draft=[];renderDraft();renderInspector();};
$('#collapseLeft').onclick=()=>{ $('main').classList.toggle('leftclosed');$('#collapseLeft').textContent=$('main').classList.contains('leftclosed')?'›':'‹';};
function applySearch(){let s=$('#search').value.toLowerCase();$$('.hierarchy .treeitem').forEach(b=>b.hidden=!!s&&!b.textContent.toLowerCase().includes(s));}
$('#search').oninput=applySearch;
$('#pause').onclick=()=>{state.paused=!state.paused;$('#pause').textContent=state.paused?'▶':'Ⅱ';$('#pause').setAttribute('aria-label',state.paused?'시뮬레이션 재개':'시뮬레이션 일시정지');};
$('#speed').onclick=()=>{state.speed=state.speed===1?2:state.speed===2?4:1;$('#speed').textContent=state.speed+'×';};
$('#gridBtn').onclick=()=>{let hidden=$('#gridLayer').style.display==='none';$('#gridLayer').style.display=hidden?'':'none';$('#gridBtn').setAttribute('aria-pressed',String(hidden));};
function view(){let v=state.view;$('#map').setAttribute('viewBox',[v.x,v.y,v.w,v.h].join(' '));$('#zoomLabel').textContent=Math.round(1000/v.w*100)+'%';}
$('#homeView').onclick=()=>{state.view={x:0,y:0,w:1000,h:760};view();};
function point(e){let p=$('#map').createSVGPoint();p.x=e.clientX;p.y=e.clientY;return p.matrixTransform($('#map').getScreenCTM().inverse());}
let gesture;
$('#map').addEventListener('pointerdown',e=>{if(e.button!==0)return;let p=point(e);gesture={p,x:e.clientX,y:e.clientY,view:{...state.view},target:e.target.closest('[data-id]')?.dataset.id};$('#map').setPointerCapture(e.pointerId);});
$('#map').addEventListener('pointermove',e=>{let p=point(e);$('#coordinates').textContent='X '+Math.round(p.x)+' · Y '+Math.round(p.y);if(!gesture)return;if(state.tool==='pan'){let scale=gesture.view.w/$('#map').getBoundingClientRect().width;state.view.x=gesture.view.x-(e.clientX-gesture.x)*scale;state.view.y=gesture.view.y-(e.clientY-gesture.y)*scale;view();}if(state.tool==='scan'){let r=$('#selectionRect');r.setAttribute('x',Math.min(gesture.p.x,p.x));r.setAttribute('y',Math.min(gesture.p.y,p.y));r.setAttribute('width',Math.abs(p.x-gesture.p.x));r.setAttribute('height',Math.abs(p.y-gesture.p.y));r.setAttribute('visibility','visible');}});
$('#map').addEventListener('pointerup',e=>{if(!gesture)return;let g=gesture;gesture=null;$('#selectionRect').setAttribute('visibility','hidden');let p=point(e);if(state.tool==='scan'){if(Math.abs(p.x-g.p.x)<15||Math.abs(p.y-g.p.y)<15){toast('해역 위에서 영역을 드래그하세요.');return;}if(state.scan){toast('탐사가 이미 진행 중입니다.');return;}if(state.orders.length>=4){toast('사용 가능한 연산코어가 없습니다.');return;}state.scan={x:Math.max(30,Math.min(950,(g.p.x+p.x)/2)),y:Math.max(30,Math.min(720,(g.p.y+p.y)/2)),progress:0};renderOrders();log('탐사 영역 지정 / SURVEY-01 분석 시작','SCAN');return;}if(g.target&&state.tool!=='pan'){if(state.tool==='route'){if(state.draft.at(-1)!==g.target)state.draft.push(g.target);renderDraft();}select(g.target);}});
$('#map').addEventListener('pointercancel',()=>{gesture=null;$('#selectionRect').setAttribute('visibility','hidden');});
$('#map').addEventListener('wheel',e=>{e.preventDefault();let p=point(e),v=state.view,f=e.deltaY>0?1.1:.9,w=Math.max(400,Math.min(1800,v.w*f)),ratio=w/v.w;state.view={x:p.x-(p.x-v.x)*ratio,y:p.y-(p.y-v.y)*ratio,w,h:v.h*ratio};view();},{passive:false});
document.addEventListener('keydown',e=>{if(e.key==='Escape'){gesture=null;state.draft=[];renderDraft();$('#selectionRect').setAttribute('visibility','hidden');$('#panelPicker').hidden=true;setTool('select');}});
document.addEventListener('pointerover',e=>{let target=e.target.closest('[data-node]');if(!target)return;let n=nodes.find(n=>n.id===target.dataset.node);$('#hoverCard').innerHTML='<b>'+esc(n.name)+'</b><p>'+esc(n.detail)+'<br>전력: '+esc(n.power)+'<br>재고: '+esc(n.stock)+(n.purity?'<br>순도: '+n.purity+'%':'')+'</p>';$('#hoverCard').hidden=false;$('#hoverCard').style.left=Math.min(innerWidth-230,e.clientX+20)+'px';$('#hoverCard').style.top=Math.min(innerHeight-170,e.clientY+10)+'px';});
document.addEventListener('pointerout',e=>{if(e.target.closest('[data-node]'))$('#hoverCard').hidden=true;});
$('#saveLayout').onclick=()=>{try{let data={version:1,note:state.note,closed:$('main').classList.contains('leftclosed'),windows:$$('.floating').map(w=>({id:w.id.slice(7),x:w.offsetLeft,y:w.offsetTop,w:w.offsetWidth,h:w.offsetHeight}))};localStorage.setItem('pelagic-layout-v1',JSON.stringify(data));toast('창 배치와 계산 메모를 저장했습니다. 게임 진행은 저장하지 않습니다.');}catch{toast('이 환경에서는 저장할 수 없습니다.');}};
$('#restoreLayout').onclick=()=>{try{let d=JSON.parse(localStorage.getItem('pelagic-layout-v1'));if(!d||d.version!==1||!Array.isArray(d.windows)){toast('저장된 배치가 없습니다.');return;}$$('.floating').forEach(w=>w.remove());state.note=typeof d.note==='string'?d.note:undefined;$('main').classList.toggle('leftclosed',!!d.closed);d.windows.filter(w=>panels[w.id]&&[w.x,w.y,w.w,w.h].every(Number.isFinite)).forEach(w=>openPanel(w.id,w));toast('저장한 작업영역을 복원했습니다.');}catch{toast('배치 파일을 읽을 수 없습니다.');}};
let contours='';for(let i=0;i<13;i++){contours+='<path d="M '+(-170+i*21)+' 790 Q '+(140+i*13)+' '+(710-i*13)+' '+(95+i*18)+' '+(480-i*10)+' T '+(70+i*14)+' '+(240-i*11)+' T '+(400+i*20)+' -60" fill="none" stroke="#497071" stroke-width=".7" opacity="'+(.13+i*.012)+'"/>';contours+='<path d="M '+(620+i*24)+' 800 Q '+(850+i*22)+' 620 '+(800+i*21)+' 470 T '+(1070+i*22)+' 160" fill="none" stroke="#4a6c6f" stroke-width=".7" opacity=".18"/>';}$('#contours').innerHTML=contours;
renderNodes();renderInspector();setTool('select');updateQuests();log('인터페이스 초기화 완료. 실제 경제·전투는 아직 연결되지 않았습니다.');log('MAIN QUEST 01 수신 / 임무 기록을 확인하십시오.','MISSION');
setInterval(()=>{if(state.paused)return;state.time+=state.speed;$('#clock').textContent='DAY 01 · '+stamp();if(state.scan){let s=state.scan;s.progress=Math.min(12,s.progress+state.speed);$('#scanLayer').innerHTML='<g transform="translate('+s.x+' '+s.y+')"><circle r="65" fill="#a0c8aa09" stroke="#9bbfa4" stroke-dasharray="4 6"/><text y="-80" text-anchor="middle" class="maplabel">SURVEY '+Math.round(s.progress/12*100)+'%</text></g>';if(s.progress>=12){if(!state.discovered){nodes.push({id:'quartz',name:'N-042 / 석영 광층',x:s.x,y:s.y,type:'석영',purity:72,rate:35,stock:'0 / 400',power:'연결 없음',detail:'신규 발견 · 채굴 준비 가능'});state.discovered=true;log('새 노드 발견 / N-042 석영 · 순도 72%','SCAN');renderNodes();}else log('선택 해역 추가 조사 완료 / 기존 탐사 정보 갱신','SCAN');state.scan=null;$('#scanLayer').innerHTML='';state.quest.scan=true;renderOrders();updateQuests();toast('탐사 완료 · 연산코어 반환');}}},1000);
