'use strict';
(()=>{
const M=window.ProductionModel,W=window.Workspace,NS='http://www.w3.org/2000/svg';
const boards={production:new M.Board('production'),planning:new M.Board('planning')};
const editors={}, fmt=v=>Number(v||0).toLocaleString('en-US',{maximumFractionDigits:2});
let infoSelection=null;
let gesture=null,menuContext=null,suppressClick=false;
const menu=document.createElement('div');menu.className='ne-menu';menu.id='editorAddMenu';menu.hidden=true;document.body.append(menu);
const deleteButton=document.createElement('button');deleteButton.id='edgeDeleteButton';deleteButton.className='ne-wire-delete';deleteButton.textContent='×';deleteButton.title='선택 연결 삭제';deleteButton.setAttribute('aria-label','선택 연결 삭제');deleteButton.hidden=true;document.body.append(deleteButton);
const kindNames={material:'물품',power:'전력',plan:'계획'};
const networkNames={power:'전력',production:'정제',processing:'가공'},facilityNames={lab:'연구소',producer:'생산기지',storage:'창고'};
function seed(){
 const b=boards.production,p=b.add('network',35,30,'power'),r=b.add('resource',35,440,'iron'),g=b.add('network',415,235,'processing'),s=b.add('facility',800,20,'storage'),s2=b.add('facility',800,460,'storage');
 p.title='본부 전력 연결';g.title='제1 정제 네트워크';s.title='중간재 창고 A';s2.title='중간재 창고 B';const ps=b.add('calc',350,-200),gs=b.add('calc',780,180);ps.title='전력 분배';gs.title='정제품 분배';b.addPort(ps.id,'outputs');b.addPort(gs.id,'outputs');
 b.connect(p.id,p.outputs[0].id,ps.id,ps.inputs[0].id);b.connect(g.id,g.outputs[0].id,gs.id,gs.inputs[0].id);s.x=1160;s2.x=1160;g.x=420;r.y=500;
 b.connect(ps.id,ps.outputs[0].id,r.id,r.inputs[0].id);b.connect(ps.id,ps.outputs[1].id,g.id,g.inputs[0].id);
 b.connect(r.id,r.outputs[0].id,g.id,g.inputs[1].id);b.connect(gs.id,gs.outputs[0].id,s.id,s.inputs[0].id);b.connect(gs.id,gs.outputs[1].id,s2.id,s2.inputs[0].id);
 const q=boards.planning,plan=q.add('plan',60,70,'exploration'),fleet=q.add('fleet',480,100);q.add('plan',60,450,'research');const origin=q.add('coordinate',-280,70),destination=q.add('coordinate',870,100);origin.outputs[0].coordinate='[270,510]';destination.outputs[0].coordinate='[450,220]';q.connect(origin.id,origin.outputs[0].id,plan.id,plan.inputs[0].id);q.connect(fleet.id,fleet.outputs[0].id,destination.id,destination.outputs[0].id);
}
function options(items,current){return Object.entries(items).map(([key,name])=>'<option value="'+esc(key)+'" '+(key===current?'selected':'')+'>'+esc(name)+'</option>').join('');}
function field(n,key,label,value,attrs=''){return '<label>'+label+'<input data-field="'+key+'" value="'+esc(value)+'" '+attrs+'></label>';}
function selector(key,label,items,value){return '<label class="wide">'+label+'<select data-field="'+key+'">'+options(items,value)+'</select></label>';}
function fields(n){
 let html='';if(n.type==='network')html+=field(n,'site','시설 위치 / 거점 ID',n.site||'본부')+selector('facilityKind','시설 종류',n.subtype==='power'?{headquarters:'본부 전력',solar:'태양광',wind:'풍력'}:{standard:'기본 설비',smelter:'제련 설비',chemical:'화학 설비'},n.facilityKind||(n.subtype==='power'?'headquarters':'standard'));
 if(n.type==='coordinate')html+='<small class="wide">검색으로 좌표를 추가하고 각 출력 점을 계획에 연결하세요.</small>';
 if(n.type==='resource')html+=field(n,'rate','채굴량 / min',n.rate,'type="number" min="0" max="100000" step="1"')+field(n,'purity','순도 / 0–1',n.purity,'type="number" min="0" max="1" step=".01"');
 if(n.type==='network')html+=selector('subtype','네트워크 타입',networkNames,n.subtype)+field(n,'rate',n.subtype==='power'?'공급 / kW':'처리 한도 / min',n.rate,'type="number" min="0" max="100000"')+(n.subtype==='processing'?field(n,'efficiency','회수율 / 0–1',n.efficiency,'type="number" min="0" max="1" step=".01"'):'');
 if(n.type==='facility'){html+=selector('subtype','시설 타입',facilityNames,n.subtype);if(n.subtype==='storage')html+=field(n,'stock','현재 재고',n.stock,'type="number" min="0" max="100000"')+field(n,'capacity','최대 수용량',n.capacity,'type="number" min="0" max="100000"');else html+=field(n,'rate','처리 한도 / min',n.rate,'type="number" min="0" max="100000"');}
 if(n.type==='calc')html+=selector('subtype','계산 방식',{ratio:'입력 × 배율',efficiency:'입력 × 효율'},n.subtype)+field(n,'factor',n.subtype==='efficiency'?'효율 / 0–1':'출력 배율',n.factor,'type="number" min="0" max="'+(n.subtype==='efficiency'?1:100)+'" step=".05"');
 if(n.type==='resource'||n.type==='network'&&n.subtype!=='power'||n.type==='facility'&&n.subtype!=='storage')html+=field(n,'powerDemand','필요 전력 / kW',n.powerDemand,'type="number" min="0" max="100000"');
 if(n.type==='plan'){html+=selector('subtype','계획 타입',{research:'연구 계획',exploration:'광물탐색 계획'},n.subtype);if(n.subtype==='research')html+=selector('research','연구 목표',{'회수율 개선':'회수율 개선','고밀도 배터리':'고밀도 배터리','연산코어 증설':'연산코어 증설'},n.research);
 else html+=selector('scannerSite','스캐너 설치 거점',Object.fromEntries(nodes.map(s=>[s.id,s.name+' ['+s.x+','+s.y+']'])),n.scannerSite||nodes[0]?.id)+selector('scanMode','스캔 방식',{wide:'광범위 스캔',local:'단거리 스캔'},n.scanMode||'local')+(n.scanMode==='wide'?selector('scanResource','목표 자원',{iron:'철',copper:'구리',gas:'가스',quartz:'석영'},n.scanResource||'iron'):field(n,'radius','범위 / '+(n.radius||120),n.radius||120,'type="range" min="40" max="800" step="10"')+field(n,'scanStrength','강도 / '+(n.scanStrength||50),n.scanStrength||50,'type="range" min="10" max="100" step="10"'))+'<button data-action="queue-scan">탐사 시작 · 큐 등록</button><small>큐 등록 후 스캔 창에서 시작합니다.</small>';
 html+=field(n,'target','연결된 목적지',n.target,'readonly')+selector('priority','우선순위',{'낮음':'낮음','보통':'보통','높음':'높음'},n.priority);}
 if(n.type==='fleet'){
 const moving=n.status==='이동중';html+='<label class="wide"><input data-field="autoFill" type="checkbox" '+(n.autoFill?'checked':'')+' '+(moving?'disabled':'')+'>자동 채움 '+(n.autoFill?'ON':'OFF')+'</label><div class="wide"><div class="ne-ships-head">함종 / 요청 수량 / 배정 수량</div>'+n.ships.map((row,i)=>'<div class="ne-ship" data-ship-row="'+i+'"><select data-ship-field="type" '+(moving?'disabled':'')+'>'+options(Object.fromEntries(Object.entries(M.SHIPS).map(([k,v])=>[k,v.name])),row.type)+'</select><input aria-label="요청 함선 수량" type="number" min="0" max="999" data-ship-field="count" value="'+row.count+'" '+(moving?'disabled':'')+'>'+(n.autoFill?'<span>'+row.allocated+' / '+row.count+'</span>':'<input aria-label="수동 배정 수량" type="number" min="0" max="999" data-ship-field="manual" value="'+row.manual+'" '+(moving?'disabled':'')+'>')+'<button data-action="remove-ship" data-row="'+i+'" '+(moving?'disabled':'')+' title="함선 행 삭제">−</button></div>').join('')+'<button class="ne-ship-add" data-action="add-ship" '+(moving?'disabled':'')+'>＋ 함선 추가</button></div><label class="wide">이동 목적지<div class="ne-dispatch"><input readonly data-field="destination" value="'+esc(n.destination)+'" '+(moving?'disabled':'')+'><button data-action="dispatch" '+(moving?'disabled':'')+'>명령 양식 생성</button></div></label>';
 }return html;
}
function portHTML(b,n,side){
 if(n.type==='coordinate'){if(side==='inputs')return '';return '<div class="ne-coordinate-values">'+n.outputs.map((p,i)=>'<div class="ne-coordinate-value"><span>'+String(i+1).padStart(2,'0')+'</span><button data-action="search-coordinate" data-coordinate-port="'+p.id+'">'+esc(p.coordinate||'⌕ 좌표 검색')+'</button><button data-action="remove-port" data-port-id="'+p.id+'" data-side="outputs" '+(b.edgeAt(n.id,p.id)?'disabled':'')+' aria-label="좌표 삭제">−</button><button class="ne-dot plan" data-ne-port="'+p.id+'" data-side="outputs" data-ne-owner="'+n.id+'" aria-label="좌표 '+(i+1)+' 출력"></button></div>').join('')+'<button data-action="add-port" data-side="outputs" class="ne-coordinate-add">＋ 좌표 추가</button></div>';}
 if(n.type==='plan'&&n.subtype==='exploration'&&side==='outputs')return '';

 return '<div class="ne-port-group"><div class="ne-port-heading"><button '+(side==='outputs'&&n.type!=='calc'?'hidden':'')+' data-action="add-port" data-side="'+side+'" title="'+(side==='inputs'?'입력':'출력')+' 추가">＋</button><span>'+(side==='inputs'?'입력':'출력')+' '+n[side].length+'</span></div>'+n[side].map((p,i)=>{const e=b.edgeAt(n.id,p.id),text=e?(e.error?'연결 오류':(e.kind==='plan'?'명령 연결':fmt(e.amount)+(e.kind==='power'?' kW':' /m')+(side==='outputs'?' · '+fmt(e.share)+'%':''))):'연결없음';
 return '<div class="ne-port-row" data-side="'+side+'"><button class="ne-dot '+p.kind+' '+(e?'connected':'')+'" data-ne-port="'+p.id+'" data-side="'+side+'" data-ne-owner="'+n.id+'" aria-label="'+n.title+' '+(side==='inputs'?'입력':'출력')+' '+(i+1)+'" title="'+kindNames[p.kind]+' / '+text+'"></button><span class="port-kind">'+kindNames[p.kind]+'</span><span class="port-text '+(!e?'empty':'')+'">'+esc(text)+'</span>'+(!e&&(side==='inputs'||n.type==='calc')?'<button class="minus" data-action="remove-port" data-side="'+side+'" data-port-id="'+p.id+'" title="빈 연결점 삭제">−</button>':'')+'</div>';}).join('')+'</div>';
}
function metrics(n){if(n.type==='coordinate')return '<div>좌표 출력 <b>'+n.outputs.length+'개</b></div>';if(n.type==='fleet')return '<div>예상 전투력 <b data-live="combat">'+fmt(n.combat)+'</b></div><div>편성 <b data-live="ready">'+(n.ready?'편성완료':'미완료 · 함선 부족')+'</b></div><div>상태 <b data-live="status">'+n.status+'</b></div>';
 if(n.type==='plan')return '<div>계획 상태 <b>검토 중</b></div><div>우선순위 <b>'+n.priority+'</b></div>';
 return '<div>입력 합계 <b>'+fmt(n.inputAmount)+' / min</b></div><div>가용 전력 <b>'+fmt(n.power)+' kW</b></div><div>배출 / 산출 가능 <b>'+fmt(n.flow)+' / '+fmt(n.planned)+(n.type==='network'&&n.subtype==='power'?' kW':' /m')+'</b></div>';
}
function renderNode(b,n){const errors=n.errors||[],warnings=n.warnings||[],copy=n.type==='plan'?'<div class="ne-plan-copy">'+(n.subtype==='research'?({'회수율 개선':'정제 연구 · 철재 120 / 구리 40 · 예상 4분','고밀도 배터리':'축전 연구 · 축전 소재 80 / 구리 60 · 예상 6분','연산코어 증설':'관제 연구 · 전장품 24 / 금 4 · 예상 5분'}[n.research]):'영역 탐사 · 목표 조사율 100%<br>연결된 함대의 목적지에 중심 좌표 적용')+'<br>계획 예시 · 실제 비용 소모 없음</div>':'';
 return '<article class="ne-node '+(b.selected===n.id?'selected ':'')+(errors.length?'bad':'')+(n.collapsed?' collapsed':'')+'" data-ne-node="'+n.id+'" style="left:'+n.x+'px;top:'+n.y+'px;--nodecolor:'+n.color+'"><div class="ne-header"><span class="type-dot"></span><strong>'+esc(n.title)+'</strong><button data-action="info" title="상세 정보" aria-label="상세 정보" aria-expanded="'+!!n.infoOpen+'">ⓘ</button><button data-action="collapse-node" title="'+(n.collapsed?'펼치기':'최소화')+'" aria-label="'+(n.collapsed?'펼치기':'최소화')+'">'+(n.collapsed?'□':'−')+'</button><button data-action="delete-node" title="노드 삭제" aria-label="노드 삭제"><svg width="14" height="15" viewBox="0 0 14 15"><path d="M2 4H12M5 2H9M3 4L4 13H10L11 4M6 6V11M8 6V11" fill="none" stroke="currentColor" stroke-width="1.2"/></svg></button></div><div class="node-id">'+M.TYPES[n.type].name.toUpperCase()+' / '+n.id+'</div>'+(n.type==='fleet'?'<div class="ne-metrics">'+metrics(n)+'</div>':'')+'<div class="ne-fields">'+fields(n)+'</div>'+copy+nodeExtras(b,n)+(n.type!=='fleet'?'<div class="ne-metrics">'+metrics(n)+'</div>':'')+'<div class="ne-ports">'+portHTML(b,n,'inputs')+portHTML(b,n,'outputs')+'</div><div class="ne-warning '+(errors.length?'error':warnings.length?'':'good')+'">'+(errors.length?'● '+errors.map(esc).join('<br>'):'')+(warnings.length?(errors.length?'<br>':'')+'△ '+warnings.map(esc).join('<br>'):errors.length?'':'● 연결 정상')+'</div><div class="ne-caption">타입별 색상 · '+(n.type==='fleet'?'출정 명령 양식 · 생성만으로 이동하지 않음':'정기선 효율 100% / 편집 시 재계산')+'</div></article>';
}
function nodePoint(ed,nodeId,portId){const dot=ed.nodes.querySelector('[data-ne-port="'+portId+'"][data-ne-owner="'+nodeId+'"]');if(!dot)return{x:0,y:0};const r=dot.getBoundingClientRect(),v=ed.viewport.getBoundingClientRect(),b=ed.board;return{x:(r.x+r.width/2-v.x-b.view.x)/b.view.scale,y:(r.y+r.height/2-v.y-b.view.y)/b.view.scale};}
function edgePoints(ed,e){const a=nodePoint(ed,e.from,e.out),b=nodePoint(ed,e.to,e.in);if(ed.board.lineMode==='curve'){const dx=Math.max(75,Math.abs(b.x-a.x)*.45);return{a,b,d:'M'+a.x+','+a.y+' C'+(a.x+dx)+','+a.y+' '+(b.x-dx)+','+b.y+' '+b.x+','+b.y};}
 const mid=(a.x+b.x)/2+(Number.isFinite(e.routeOffset)?e.routeOffset:0),pts=[a,{x:mid,y:a.y},{x:mid,y:b.y},b];
 return{a,b,pts,d:pts.map((p,i)=>(i?'L':'M')+p.x+','+p.y).join(' ')};}
function renderWires(ed){const b=ed.board;if(!ed.viewport.getBoundingClientRect().width)return;
 ed.wires.innerHTML=b.edges.map(e=>{const geo=edgePoints(ed,e),n=b.node(e.from),sel=b.selectedEdge===e.id,flow=b.selected===e.from||b.selected===e.to;
 let segments='';if(b.lineMode==='straight')segments=geo.pts.slice(0,-1).map((p,i)=>{const q=geo.pts[i+1];return '<path class="bend-segment" data-segment="'+i+'" data-edge="'+e.id+'" style="cursor:'+'ew'+'-resize" d="M'+p.x+','+p.y+'L'+q.x+','+q.y+'"/>';}).join('');
 return '<g data-edge-group="'+e.id+'" style="--wire:'+n.color+'"><path class="edge-line '+(e.error?'error ':'')+(flow?'flowing ':'')+(sel?'selected':'')+'" d="'+geo.d+'"/><path class="edge-hit" data-edge="'+e.id+'" d="'+geo.d+'"/>'+segments+'<text class="edge-label" x="'+((geo.a.x+geo.b.x)/2+8)+'" y="'+((geo.a.y+geo.b.y)/2-8)+'">'+(e.error?'중단':n.type==='coordinate'?esc(n.outputs.find(p=>p.id===e.out)?.coordinate||'좌표 미지정'):fmt(e.share)+'% · '+fmt(e.amount))+'</text></g>';}).join('');}
function render(ed){ed.board.recompute();if(infoSelection?.ed===ed)showInformation();renderGroups(ed);ed.nodes.innerHTML=ed.board.nodes.map(n=>renderNode(ed.board,n)).join('');transform(ed);renderWires(ed);ed.status.innerHTML='<span>'+ed.board.nodes.length+' NODES / '+ed.board.edges.length+' LINKS</span><span>재계산 #'+ed.board.revision+'</span><span class="errors">'+ed.board.nodes.filter(n=>n.errors.length).length+' 오류</span><span>실제 자원·해역과 분리된 편집 시험</span>';ed.empty.hidden=!!ed.board.nodes.length;ed.root.querySelector('[data-action="collapse-all"]').textContent=ed.board.nodes.length&&ed.board.nodes.every(n=>n.collapsed)?'모두 최대화':'모두 최소화';}
function transform(ed){const v=ed.board.view;ed.viewport.style.backgroundPosition=v.x+'px '+v.y+'px';ed.viewport.style.backgroundSize=(22*v.scale)+'px '+(22*v.scale)+'px';ed.stage.style.transform='none';ed.stage.style.zoom=v.scale;ed.stage.style.left=(Math.round(v.x*devicePixelRatio)/devicePixelRatio/v.scale)+'px';ed.stage.style.top=(Math.round(v.y*devicePixelRatio)/devicePixelRatio/v.scale)+'px';ed.zoom.textContent=Math.round(v.scale*100)+'%';}
function fit(ed){const b=ed.board;if(!b.nodes.length){b.view={x:40,y:35,scale:1};transform(ed);return;}const minX=Math.min(...b.nodes.map(n=>n.x),...b.groups.map(g=>g.x)),minY=Math.min(...b.nodes.map(n=>n.y),...b.groups.map(g=>g.y)),maxX=Math.max(...b.nodes.map(n=>n.x+292),...b.groups.map(g=>g.x+g.w)),maxY=Math.max(...b.nodes.map(n=>n.y+(ed.nodes.querySelector('[data-ne-node="'+n.id+'"]')?.offsetHeight||400)),...b.groups.map(g=>g.y+g.h));
 const r=ed.viewport.getBoundingClientRect();if(!r.width)return;b.view.scale=Math.min(1.1,Math.max(.3,Math.min((r.width-70)/(maxX-minX),(r.height-65)/(maxY-minY))));b.view.x=(r.width-(maxX-minX)*b.view.scale)/2-minX*b.view.scale;b.view.y=25-minY*b.view.scale;transform(ed);renderWires(ed);}
function worldPoint(ed,e){const r=ed.viewport.getBoundingClientRect(),v=ed.board.view;return{x:(e.clientX-r.x-v.x)/v.scale,y:(e.clientY-r.y-v.y)/v.scale};}
function showAdd(ed,e){const p=worldPoint(ed,e);menuContext={ed,p,client:{x:e.clientX,y:e.clientY}};let content='';
 if(ed.board.kind==='production'){content='<div class="menu-group">연결되지 않은 자원 노드</div>'+Object.entries(M.RESOURCES).map(([key,r])=>'<button data-create="resource" data-sub="'+key+'" '+(ed.board.nodes.some(n=>n.type==='resource'&&n.subtype===key)?'disabled':'')+'>'+r.name+'<small>순도 '+r.purity*100+'%</small></button>').join('')+'<div class="menu-group">네트워크 구성 · 내부 타입 선택</div><button data-create="network" data-sub="power">네트워크<small>전력 / 정제 / 가공</small></button><div class="menu-group">본부 특수시설</div><button data-create="facility" data-sub="storage">시설<small>연구소 / 생산기지 / 창고</small></button><div class="menu-group">계산</div><button data-create="calc">입출력 계산<small>배율 / 효율</small></button>';}
 else content='<button data-create="coordinate">좌표<small>검색한 좌표 문자열 · 개별 출력</small></button><div class="menu-group">계획 노드</div><button data-create="plan" data-sub="research">계획<small>연구 / 탐사</small></button><button data-create="plan" data-sub="exploration">광물탐색 계획<small>스캐너 / 탐사 큐</small></button><div class="menu-group">함대</div><button data-create="fleet">함대 편성<small>자동 채움 / 출정</small></button>';
 content+='<div class="menu-group">보기 정리</div><button data-create="group">그룹 지정<small>영역 드래그 · 생산 영향 없음</small></button>';menu.innerHTML=content;menu.hidden=false;menu.style.left=Math.max(5,Math.min(innerWidth-255,e.clientX+12))+'px';menu.style.top=Math.max(55,Math.min(innerHeight-menu.offsetHeight-8,e.clientY))+'px';deleteButton.hidden=true;
}
function selectNode(ed,id){ed.board.selected=id;ed.board.selectedEdge=null;ed.nodes.querySelectorAll('.ne-node').forEach(n=>n.classList.toggle('selected',n.dataset.neNode===id));deleteButton.hidden=true;renderWires(ed);}
function selectEdge(ed,id,e){ed.board.selectedEdge=id;renderWires(ed);deleteButton.dataset.board=ed.board.kind;deleteButton.dataset.edge=id;deleteButton.style.left=Math.max(5,Math.min(innerWidth-40,e.clientX+8))+'px';deleteButton.style.top=Math.max(55,Math.min(innerHeight-35,e.clientY-24))+'px';deleteButton.hidden=false;}
function restoreOriginal(g){if(g.original&&!g.ed.board.edgeAt(g.original.from,g.original.out)&&!g.ed.board.edgeAt(g.original.to,g.original.in)){g.ed.board.edges.push(g.original);g.ed.board.recompute();}}
function finishWire(e,cancel=false){const g=gesture;if(!g||g.kind!=='wire')return;const ed=g.ed,b=ed.board;gesture=null;ed.ghost.innerHTML='';
 if(cancel){restoreOriginal(g);render(ed);return;}
 const dot=document.elementFromPoint(e.clientX,e.clientY)?.closest('[data-ne-port]'),targetBoard=dot?.closest('.node-editor')?.dataset.board;
 if(dot&&targetBoard===b.kind){const side=dot.dataset.side;if(side===g.anchor.side){const result=side==='outputs'?b.connect(g.anchor.node,g.anchor.port,dot.dataset.neOwner,dot.dataset.nePort,'outputs'):{ok:false,error:'출력과 입력을 연결하세요.'};if(!result.ok){restoreOriginal(g);toast(result.error);}}
 else{const from=g.anchor.side==='outputs'?g.anchor:{node:dot.dataset.neOwner,port:dot.dataset.nePort,side},to=g.anchor.side==='inputs'?g.anchor:{node:dot.dataset.neOwner,port:dot.dataset.nePort,side};const result=b.connect(from.node,from.port,to.node,to.port);if(!result.ok){restoreOriginal(g);toast(result.error);}else log('편집 연결 업데이트 / 효율 재계산','GRAPH');}}
 else if(g.original)log('편집 연결 해제 / 빈 곳에 놓음','GRAPH');
 render(ed);suppressClick=true;setTimeout(()=>suppressClick=false,0);
}
function beginWire(ed,dot,e){const b=ed.board,old=b.edgeAt(dot.dataset.neOwner,dot.dataset.nePort);let anchor={node:dot.dataset.neOwner,port:dot.dataset.nePort,side:dot.dataset.side};if(old){anchor=old.from===dot.dataset.neOwner&&old.out===dot.dataset.nePort?{node:old.to,port:old.in,side:old.toSide||'inputs'}:{node:old.from,port:old.out,side:'outputs'};b.edges=b.edges.filter(l=>l.id!==old.id);b.recompute();}
 gesture={kind:'wire',ed,anchor,original:old?structuredClone(old):null,sx:e.clientX,sy:e.clientY,moved:false,sticky:false};
 render(ed);menu.hidden=true;deleteButton.hidden=true;e.preventDefault();}
function editField(ed,target){const b=ed.board,n=b.node(target.closest('[data-ne-node]')?.dataset.neNode);if(!n)return;
 if(target.dataset.portKind){const p=n[target.dataset.side].find(p=>p.id===target.dataset.portKind);if(p)p.kind=target.value;}
 else if(target.dataset.shipField){if(n.status==='이동중')return;let row=n.ships[Number(target.closest('[data-ship-row]').dataset.shipRow)],key=target.dataset.shipField;row[key]=key==='type'?target.value:Math.floor(Math.max(0,Math.min(999,Number(target.value)||0)));}
 else{const key=target.dataset.field;if(key==='subtype')b.subtype(n.id,target.value);else if(key==='autoFill')n.autoFill=target.checked;else if(['coordinate','title','target','research','priority','destination','site','facilityKind','scannerSite','scanMode','scanResource'].includes(key))n[key]=target.value.slice(0,100);else{let v=Number(target.value);if(!Number.isFinite(v)){toast('유효한 숫자를 입력하세요.');render(ed);return;}n[key]=Math.max(0,Math.min(['purity','efficiency'].includes(key)||key==='factor'&&n.subtype==='efficiency'?1:key==='factor'?100:100000,v));}}
 render(ed);}
function action(ed,el){const b=ed.board,n=b.node(el.closest('[data-ne-node]')?.dataset.neNode),a=el.dataset.action;if(n)b.selected=n.id;
 if(a==='clear-nodes'){if(b.nodes.length&&!confirm('그룹은 남기고 모든 계획 노드와 연결을 삭제할까요?'))return;b.nodes=[];b.edges=[];b.selected=null;b.selectedEdge=null;render(ed);return;}
 if(a==='fit'){fit(ed);return;}
 if(a==='collapse-all'){const collapse=!b.nodes.length?false:!b.nodes.every(n=>n.collapsed);b.nodes.forEach(n=>n.collapsed=collapse);render(ed);return;}
 if(a==='queue-scan'){window.ScanUI?.enqueue(n);return;}
 if(a==='auto-layout'){autoLayout(ed);return;}
 if(a==='info'){if(n){infoSelection={ed,id:n.id};showInformation();W.activate('nodeinfo');}return;}
 if(a==='facility-tab'){if(n){n.facilityTab=el.dataset.facilityView;render(ed);}return;}if(a==='mode'){b.lineMode=b.lineMode==='curve'?'straight':'curve';ed.root.querySelector('[data-action="mode"]').textContent=b.lineMode==='curve'?'∿ 곡선 S':'⌁ 직선 S';ed.root.querySelector('[data-action="mode"]').setAttribute('aria-pressed',b.lineMode==='straight');deleteButton.hidden=true;renderWires(ed);return;}
 if(a==='save'){try{localStorage.setItem('pelagic-graph-'+b.kind+(b.kind==='planning'&&window.PlanningUI?'-'+PlanningUI.active:''),JSON.stringify({version:1,kind:b.kind,nodes:b.nodes,edges:b.edges,groups:b.groups,lineMode:b.lineMode,view:b.view}));toast('편집 그래프를 저장했습니다.');}catch{toast('그래프를 저장할 수 없습니다.');}return;}
 if(a==='load'){loadGraph(ed);return;}if(!n)return;
 if(a==='collapse-node')n.collapsed=!n.collapsed;
 if(a==='delete-node'){b.removeNode(n.id);deleteButton.hidden=true;}
 if(a==='add-port')b.addPort(n.id,el.dataset.side);
 if(a==='remove-port')b.removePort(n.id,el.dataset.portId,el.dataset.side);
 if(a==='add-ship'&&n.status!=='이동중')n.ships.push({type:'guard',count:1,manual:0});
 if(a==='remove-ship'&&n.status!=='이동중')n.ships.splice(Number(el.dataset.row),1);
 if(a==='search-coordinate'){window.PlanningUI?.search(b,n,el.dataset.coordinatePort);return;}
 if(a==='dispatch'){window.PlanningUI?.compile(b,n);return;}
 render(ed);}
function loadGraph(ed){
 try{const d=JSON.parse(localStorage.getItem('pelagic-graph-'+ed.board.kind+(ed.board.kind==='planning'&&window.PlanningUI?'-'+PlanningUI.active:'')));if(!d||d.version!==1||d.kind!==ed.board.kind||!Array.isArray(d.nodes)||!Array.isArray(d.edges)||d.nodes.length>100||d.edges.length>400)throw Error();
 const ids=new Set(),portIds=new Set();const fresh=new M.Board(d.kind);
 for(const raw of d.nodes){if(!M.TYPES[raw.type]||!Number.isFinite(raw.x)||!Number.isFinite(raw.y)||ids.has(raw.id)||typeof raw.id!=='string')throw Error();ids.add(raw.id);
 const allowed=d.kind==='production'?['resource','network','facility','calc']:['coordinate','plan','fleet'];if(!allowed.includes(raw.type))throw Error();
 const n=M.createNode(raw.type,raw.x,raw.y,raw.subtype);n.id=raw.id;n.collapsed=!!raw.collapsed;
 for(const key of ['rate','purity','efficiency','factor','powerDemand','capacity','stock','radius','scanStrength'])if(Number.isFinite(raw[key]))n[key]=Math.max(0,Math.min(100000,raw[key]));
 for(const key of ['coordinate','title','research','target','priority','location','destination','site','facilityKind','facilityTab','scannerSite','scanMode','scanResource'])if(typeof raw[key]==='string')n[key]=raw[key].slice(0,100);
 if(raw.type==='resource'&&!M.RESOURCES[n.subtype]||raw.type==='network'&&!networkNames[n.subtype]||raw.type==='facility'&&!facilityNames[n.subtype]||raw.type==='calc'&&!['ratio','efficiency'].includes(n.subtype)||raw.type==='plan'&&!['research','exploration'].includes(n.subtype))throw Error();
 n.purity=Math.min(1,n.purity);n.efficiency=Math.min(1,n.efficiency);n.factor=Math.min(n.subtype==='efficiency'?1:100,n.factor);
 for(const side of ['inputs','outputs']){if(!Array.isArray(raw[side])||raw[side].length>24)throw Error();n[side]=raw[side].map(p=>{if(typeof p.id!=='string'||portIds.has(p.id)||!kindNames[p.kind])throw Error();portIds.add(p.id);return{id:p.id,kind:p.kind,...(n.type==='coordinate'?{coordinate:p.coordinate??raw.coordinate??'',siteId:p.siteId}:{})};});}
 if(n.type==='fleet'){if(!Array.isArray(raw.ships)||raw.ships.length>30)throw Error();n.autoFill=!!raw.autoFill;n.ships=raw.ships.map(row=>{if(!M.SHIPS[row.type])throw Error();return{type:row.type,count:Math.floor(Math.max(0,Math.min(999,Number(row.count)||0))),manual:Math.floor(Math.max(0,Math.min(999,Number(row.manual)||0)))};});n.status='대기중';n.travel=0;}
 fresh.nodes.push(n);
 }
 fresh.normalizePlanning();for(const raw of d.edges){if(fresh.node(raw.from)?.subtype==='exploration')continue;const result=fresh.connect(raw.from,raw.out,raw.to,raw.in,raw.toSide);if(!result.ok)throw Error();if(Number.isFinite(raw.routeOffset))result.edge.routeOffset=raw.routeOffset;}
 fresh.groups=(Array.isArray(d.groups)?d.groups:[]).slice(0,100).filter(g=>['x','y','w','h'].every(k=>Number.isFinite(g[k]))).map((g,i)=>({id:'group-'+i+'-'+Date.now(),auto:!!g.auto,x:g.x,y:g.y,w:Math.max(160,g.w),h:Math.max(90,g.h),title:String(g.title||'그룹').slice(0,60),color:['#799e91','#aa9475','#9b88ad'].includes(g.color)?g.color:'#799e91'}));
 for(const n of [...fresh.nodes])if(fresh.kind==='production'&&n.type!=='calc'&&n.outputs.length>1){const split=M.createNode('calc',n.x+330,n.y);split.title='분배 / '+n.title;split.outputs=n.outputs;split.inputs[0].kind=n.outputs[0].kind;const out=M.createNode(n.type,0,0,n.subtype).outputs[0];n.outputs=[out];for(const edge of fresh.edges)if(edge.from===n.id)edge.from=split.id;fresh.nodes.push(split);fresh.connect(n.id,out.id,split.id,split.inputs[0].id);}
 fresh.lineMode=d.lineMode==='straight'?'straight':'curve';if(d.view&&['x','y','scale'].every(k=>Number.isFinite(d.view[k])))fresh.view={x:d.view.x,y:d.view.y,scale:Math.max(.25,Math.min(1.8,d.view.scale))};
 // Loaded IDs are remapped to fresh IDs, preventing collisions with later additions.
 const nodeMap=new Map(),pMap=new Map();fresh.nodes.forEach(n=>{const temp=M.createNode(n.type,n.x,n.y,n.subtype);nodeMap.set(n.id,temp.id);n.id=temp.id;for(const side of ['inputs','outputs'])n[side].forEach(p=>{const tempNode=M.createNode('calc',0,0);pMap.set(p.id,tempNode.outputs[0].id);p.id=tempNode.outputs[0].id;});});fresh.edges.forEach(e=>{e.from=nodeMap.get(e.from);e.to=nodeMap.get(e.to);e.out=pMap.get(e.out);e.in=pMap.get(e.in);});
 boards[d.kind]=fresh;ed.board=fresh;render(ed);ed.root.querySelector('[data-action="mode"]').textContent=fresh.lineMode==='curve'?'∿ 곡선 S':'⌁ 직선 S';toast('그래프 복원 · 이동 상태는 대기로 복원됩니다.');
 }catch{toast('저장된 그래프가 없거나 형식이 잘못되었습니다. 현재 그래프를 유지합니다.');}
}

function facilityMembers(b,n){
 const seen=new Set([n.id]),pending=[n.id];
 while(pending.length){const id=pending.pop();for(const e of b.edges.filter(e=>!e.error&&(e.from===id||e.to===id))){const other=b.node(e.from===id?e.to:e.from);if(!other||seen.has(other.id))continue;if(other.type==='calc'||other.type==='network'&&other.subtype===n.subtype&&(other.site||'본부').trim()===(n.site||'본부').trim()){seen.add(other.id);pending.push(other.id);}}}
 return b.nodes.filter(x=>seen.has(x.id)&&x.type==='network'&&x.subtype===n.subtype);
}
function nodeExtras(b,n,detail=false){
 let h='';
 if(n.type==='network'){
 const members=facilityMembers(b,n),open=n.facilityTab==='group',label=networkNames[n.subtype]+'시설 그룹';
 h+='<div class="ne-facility-tabs"><button data-action="facility-tab" data-facility-view="summary" aria-pressed="'+!open+'">운영 요약</button><button data-action="facility-tab" data-facility-view="group" aria-pressed="'+open+'">'+label+' · '+members.length+'</button></div>';
 h+='<div class="ne-facility-summary">'+(open?'<b>'+esc(n.site||'본부')+' / 연결 시설 '+members.length+'개</b>'+members.map(x=>'<div>'+esc(x.title)+' · '+esc(({headquarters:'본부 전력',solar:'태양광',wind:'풍력',standard:'기본 설비',smelter:'제련 설비',chemical:'화학 설비'})[x.facilityKind]||networkNames[x.subtype])+' · '+fmt(x.rate)+(x.subtype==='power'?' kW':' /min')+'</div>').join('')+'<small>동일 위치 ID + 유효 연결로 자동 분류 · 화면상의 위치와 무관</small>':'위치 '+esc(n.site||'본부')+' · '+members.length+'개 시설이 같은 연결 그룹')+'</div>';
 }
 if(!detail)return h;
 const formulas={coordinate:'각 출력은 검색으로 선택한 독립 좌표 문자열입니다. 함대 출력에도 연결할 수 있습니다.',resource:'채굴량 × 전력 충족률. 순도는 연결된 가공시설의 회수량에 반영됩니다.',network:n.subtype==='power'?'설정 공급량을 전력으로 배출합니다.':n.subtype==='production'?'min(입력량, 처리 한도) × 전력 충족률. 현재 정제의 기본 통과 계산입니다.':'min(입력량, 처리 한도) × 입력 순도 × 회수율 × 전력 충족률.',calc:'입력 합계 × 배율(또는 효율). 연결된 출력 수로 균등 분배합니다. 빈 출력은 제외합니다.',facility:n.subtype==='storage'?'현재 재고가 수용량에 도달하면 들어오는 정기선이 중단됩니다.':'처리 한도와 전력 충족률에 따라 처리합니다. 생산기지는 현재 80% 변환 예시입니다.',plan:'계획 정보를 보관합니다. 연결된 탐사 계획은 함대의 목적지에 적용됩니다. 연구 비용과 진행은 아직 예시입니다.',fleet:'배정된 함선 수 × 함종별 전투력의 합. 편성 완료 시 약 8초 이동 시험이 가능합니다.'};
 const links=b.edges.filter(e=>e.from===n.id||e.to===n.id);
 h+='<section class="ne-information"><b>상세 정보 / '+esc(n.title)+'</b><dl><dt>식별자 · 타입</dt><dd>'+esc(n.id)+' · '+esc(M.TYPES[n.type].name)+' / '+esc(networkNames[n.subtype]||facilityNames[n.subtype]||n.subtype)+'</dd><dt>계산 규칙</dt><dd>'+formulas[n.type]+'</dd><dt>현재 수치</dt><dd>입력 '+fmt(n.inputAmount)+' /min · 전력 '+fmt(n.power)+' kW<br>산출 가능 '+fmt(n.planned)+' · 실제 배출 '+fmt(n.flow)+'</dd><dt>입출력</dt><dd>입력 '+n.inputs.length+'개 / 출력 '+n.outputs.length+'개<br>점 하나당 연결 하나 · 정기선 효율 100%</dd><dt>연결 상세</dt><dd>'+(links.length?links.map(e=>esc(b.node(e.from)?.title)+' → '+esc(b.node(e.to)?.title)+'<br>'+fmt(e.amount)+' · '+fmt(e.share)+'%'+(e.error?' · '+esc(e.error):'')).join('<hr>'):'연결 없음')+'</dd><dt>진단</dt><dd>'+[...n.errors,...n.warnings].map(esc).join('<br>')+'</dd><dt>시험판 범위</dt><dd>실제 시설 건설·자원 차감·시간별 재고 누적과 분리된 편집 시험입니다. 최소화와 정리 그룹은 생산량을 바꾸지 않습니다.</dd></dl></section>';
 return h;
}
function autoLayoutPlans(ed){
 const b=ed.board,remaining=new Set(b.nodes.map(n=>n.id));b.groups=b.groups.filter(g=>!g.auto);let top=50,index=0;
 while(remaining.size){const ids=new Set(),queue=[remaining.values().next().value];while(queue.length){const id=queue.shift();if(!remaining.delete(id))continue;ids.add(id);for(const edge of b.edges){if(edge.from===id&&remaining.has(edge.to))queue.push(edge.to);if(edge.to===id&&remaining.has(edge.from))queue.push(edge.from);}}
 const items=b.nodes.filter(n=>ids.has(n.id)),columns=[[],[],[]];
 for(const n of items){const incoming=b.edges.some(e=>e.from===n.id&&e.toSide==='outputs'&&ids.has(e.to));columns[n.type==='coordinate'?(incoming?2:0):1].push(n);}
 let bottom=top+140;columns.forEach((nodes,col)=>{let y=top+55;for(const n of nodes){n.x=64+col*425;n.y=y;y+=(ed.nodes.querySelector('[data-ne-node="'+n.id+'"]')?.offsetHeight||350)+35;}bottom=Math.max(bottom,y);});
 b.groups.push({id:'auto-plan-'+(++index),auto:true,title:'출정 묶음 '+index,x:40,y:top,w:1190,h:bottom-top,color:'#799e91'});top=bottom+65;
 }
 b.edges.forEach(e=>{delete e.waypoints;delete e.routeOffset;});render(ed);fit(ed);toast('연결된 묶음별 가로 배치 완료 · 출발 좌표 → 계획/편성 → 도착 좌표');
}
function autoLayout(ed){
 if(ed.board.kind==='planning'){autoLayoutPlans(ed);return;}
 const b=ed.board,rank=new Map();
 for(const n of b.nodes)if(n.type!=='calc')rank.set(n.id,n.type==='resource'?1:n.type==='network'&&n.subtype==='power'?0:n.type==='facility'&&n.subtype==='storage'||n.type==='fleet'?3:2);
 for(let i=0;i<b.nodes.length;i++)for(const n of b.nodes.filter(n=>n.type==='calc')){const src=b.edges.filter(e=>e.to===n.id&&!e.error).map(e=>rank.get(e.from)).filter(x=>x!=null);if(src.length)rank.set(n.id,Math.max(...src));}
 if(b.kind==='production')for(const n of b.nodes)rank.set(n.id,n.type==='calc'?(n.inputs[0]?.kind==='power'?1:4):[0,2,3,5][rank.get(n.id)??2]);
 b.groups=b.groups.filter(g=>!g.auto);const titles=b.kind==='production'?['전력시설','전력 분배','채광시설','정제 가공시설','물품 분배','보관시설']:['지원','탐사','연구 · 계획','함대'];
 let x=40;
 for(let k=0;k<titles.length;k++){const items=b.nodes.filter(n=>(rank.get(n.id)??2)===k);if(!items.length)continue;let y=100;for(const n of items){n.x=x+24;n.y=y;const h=ed.nodes.querySelector('[data-ne-node="'+n.id+'"]')?.offsetHeight||350;y+=h+45;}
 b.groups.push({id:'auto-'+k,auto:true,title:titles[k],x,y:50,w:340,h:y-60,color:['#aa9475','#799e91','#9b88ad','#799e91'][k%4]});x+=425;}
 b.edges.forEach(e=>{delete e.waypoints;delete e.routeOffset;});render(ed);fit(ed);toast('자동 배치 완료 · 연결과 생산 수치는 유지됩니다.');
}

function showInformation(){if(!infoSelection)return;const {ed,id}=infoSelection,n=ed.board.node(id),p=W.ensurePane('nodeinfo');p.innerHTML=n?'<div class="node-info-window">'+nodeExtras(ed.board,n,true)+'</div>':'<p class="padded">선택한 노드가 삭제되었습니다.</p>';}
function renderGroups(ed){const layer=ed.root.querySelector('.ne-groups');if(!layer)return;layer.innerHTML=ed.board.groups.map(g=>'<section class="ne-group" data-ne-group="'+g.id+'" style="left:'+g.x+'px;top:'+g.y+'px;width:'+g.w+'px;height:'+g.h+'px;--groupcolor:'+g.color+'"><div class="ne-group-title"><span title="드래그하면 내부 노드 함께 이동">⠿</span><input aria-label="그룹 이름" data-group-field="title" value="'+esc(g.title)+'"><select aria-label="그룹 색상" data-group-field="color">'+options({'#799e91':'녹색','#aa9475':'황토','#9b88ad':'보라'},g.color)+'</select><button data-delete-group title="그룹만 삭제 · 노드 유지">×</button></div><div class="ne-group-resize" title="그룹 크기 조절">◢</div></section>').join('');}
function buildEditor(kind){const pane=W.ensurePane(kind);pane.dataset.customEditor='true';pane.innerHTML='<div class="node-editor" data-board="'+kind+'"><div class="ne-toolbar"><b>'+(kind==='production'?'생산 네트워크':'계획 · 함대 편성')+'</b><button data-action="fit">시점 복원</button><button data-action="collapse-all">모두 최소화</button><button data-action="auto-layout">자동 배치</button>'+(kind==='planning'?'<button data-action="clear-nodes">그룹 외 모두 삭제</button>':'')+'<button data-action="mode" aria-pressed="false">∿ 곡선 S</button><button data-action="save">그래프 저장</button><button data-action="load">불러오기</button><span class="demo-label">독립 편집 시험</span></div><div class="ne-subtitle">빈 곳 클릭: 노드 추가 · 점 드래그: 연결 / 재배선 · 빈 곳에 놓기: 연결 해제</div><div class="ne-viewport" tabindex="0" aria-label="'+(kind==='production'?'생산관리':'계획')+' 노드 편집 영역"><div class="ne-stage"><div class="ne-groups"></div><div class="ne-group-draft" hidden></div><svg class="ne-wires"><g class="ne-edge-layer"></g><g class="ne-ghost-layer"></g></svg><div class="ne-nodes"></div></div><div class="ne-empty">빈 공간을 클릭해 첫 노드를 추가하세요.</div></div><div class="ne-statusbar"></div></div>';
 const root=pane.querySelector('.node-editor'),ed={root,board:boards[kind],viewport:root.querySelector('.ne-viewport'),stage:root.querySelector('.ne-stage'),nodes:root.querySelector('.ne-nodes'),wires:root.querySelector('.ne-edge-layer'),ghost:root.querySelector('.ne-ghost-layer'),empty:root.querySelector('.ne-empty'),status:root.querySelector('.ne-statusbar')};ed.zoom=document.createElement('span');ed.zoom.className='demo-label';root.querySelector('.ne-toolbar').append(ed.zoom);editors[kind]=ed;
 root.addEventListener('change',e=>{if(e.target.dataset.groupField){const g=ed.board.groups.find(g=>g.id===e.target.closest('[data-ne-group]').dataset.neGroup);g[e.target.dataset.groupField]=e.target.value.slice(0,60);renderGroups(ed);return;}if(e.target.matches('[data-field],[data-ship-field],[data-port-kind]'))editField(ed,e.target);});
 root.addEventListener('click',e=>{if(e.target.closest('[data-delete-group]')){const id=e.target.closest('[data-ne-group]').dataset.neGroup;ed.board.groups=ed.board.groups.filter(g=>g.id!==id);renderGroups(ed);return;}const a=e.target.closest('[data-action]');if(a){action(ed,a);return;}});
 ed.viewport.addEventListener('pointerdown',e=>{
 if(e.button!==0)return;
 if(ed.groupDraw){const p=worldPoint(ed,e);gesture={kind:'group-draw',ed,p,sx:e.clientX,sy:e.clientY,moved:false};ed.groupDraw=false;ed.viewport.classList.remove('group-drawing');e.preventDefault();return;}
 const groupEl=e.target.closest('[data-ne-group]');
 if(groupEl&&!e.target.closest('input,select,button')){const group=ed.board.groups.find(g=>g.id===groupEl.dataset.neGroup),p=worldPoint(ed,e);if(e.target.closest('.ne-group-title,.ne-group-resize')){
 const members=ed.board.nodes.filter(n=>n.x+146>=group.x&&n.x+146<=group.x+group.w&&n.y+20>=group.y&&n.y+20<=group.y+group.h).map(n=>({n,x:n.x,y:n.y}));
 gesture={kind:e.target.closest('.ne-group-resize')?'group-resize':'group-move',ed,group,p,start:{...group},members,sx:e.clientX,sy:e.clientY,moved:false};e.preventDefault();return;}}
 if(gesture?.kind==='wire'){finishWire(e);e.preventDefault();return;}
 if(e.target.closest('input,select,textarea,.ne-information,button:not([data-ne-port])'))return;const dot=e.target.closest('[data-ne-port]');if(dot){beginWire(ed,dot,e);return;}
 const closeMenu=!menu.hidden&&menuContext?.ed===ed&&Math.hypot(e.clientX-menuContext.client.x,e.clientY-menuContext.client.y)<18;menu.hidden=true;deleteButton.hidden=true;const p=worldPoint(ed,e),nEl=e.target.closest('[data-ne-node]'),edgeEl=e.target.closest('[data-edge]');
 if(edgeEl){const edge=ed.board.edges.find(l=>l.id===edgeEl.dataset.edge);gesture={kind:'edge',ed,edge,sx:e.clientX,sy:e.clientY,p,startOffset:edge.routeOffset||0,segment:edgeEl.dataset.segment!=null?Number(edgeEl.dataset.segment):null,points:ed.board.lineMode==='straight'?edgePoints(ed,edge).pts:null,moved:false};}
 else if(nEl){const n=ed.board.node(nEl.dataset.neNode);selectNode(ed,n.id);gesture={kind:'node',ed,node:n,p,start:{x:n.x,y:n.y},sx:e.clientX,sy:e.clientY,moved:false};}
 else{ed.board.selected=null;renderWires(ed);gesture={kind:'pan',ed,closeMenu,p,start:{...ed.board.view},sx:e.clientX,sy:e.clientY,moved:false};}
 ed.viewport.focus({preventScroll:true});e.preventDefault();
 });
 ed.viewport.addEventListener('wheel',e=>{if(e.target.closest('input,select,textarea,.ne-information'))return;e.preventDefault();menu.hidden=true;deleteButton.hidden=true;const p=worldPoint(ed,e),r=ed.viewport.getBoundingClientRect(),v=ed.board.view;v.scale=Math.max(.25,Math.min(1.8,v.scale*(e.deltaY>0?.9:1.1)));v.x=e.clientX-r.x-p.x*v.scale;v.y=e.clientY-r.y-p.y*v.scale;transform(ed);renderWires(ed);},{passive:false});
 const ro=new ResizeObserver(()=>{if(!ed.wasVisible&&ed.viewport.getBoundingClientRect().width){ed.wasVisible=true;fit(ed);}else renderWires(ed);});ro.observe(ed.viewport);render(ed);return ed;
}
menu.addEventListener('pointerdown',e=>{if(menuContext&&Math.hypot(e.clientX-menuContext.client.x,e.clientY-menuContext.client.y)<8){menu.hidden=true;e.preventDefault();e.stopPropagation();}},true);
menu.addEventListener('click',e=>{const btn=e.target.closest('[data-create]');if(!btn||!menuContext)return;const {ed,p}=menuContext;if(btn.dataset.create==='group'){ed.groupDraw=true;ed.viewport.classList.add('group-drawing');menu.hidden=true;toast('빈 공간에서 드래그하여 그룹 영역을 지정하세요.');return;}ed.board.add(btn.dataset.create,p.x,p.y,btn.dataset.sub);menu.hidden=true;render(ed);log('편집 노드 추가 / '+M.TYPES[btn.dataset.create].name,'GRAPH');});
deleteButton.onclick=()=>{const ed=editors[deleteButton.dataset.board];ed.board.removeEdge(deleteButton.dataset.edge);deleteButton.hidden=true;render(ed);};
document.addEventListener('pointermove',e=>{
 if(!gesture)return;const g=gesture,ed=g.ed,p=worldPoint(ed,e);g.moved=g.moved||Math.hypot(e.clientX-g.sx,e.clientY-g.sy)>5;
 if(g.kind==='wire'){const a=nodePoint(ed,g.anchor.node,g.anchor.port),dx=Math.max(60,Math.abs(p.x-a.x)*.5);ed.ghost.innerHTML='<path class="ne-ghost" d="M'+a.x+','+a.y+' C'+(a.x+(g.anchor.side==='outputs'?dx:-dx))+','+a.y+' '+p.x+','+p.y+' '+p.x+','+p.y+'"/>';return;}
 if(!g.moved)return;
 if(g.kind==='group-draw'){const d=ed.root.querySelector('.ne-group-draft');d.hidden=false;Object.assign(d.style,{left:Math.min(p.x,g.p.x)+'px',top:Math.min(p.y,g.p.y)+'px',width:Math.abs(p.x-g.p.x)+'px',height:Math.abs(p.y-g.p.y)+'px'});return;}
 if(g.kind==='group-move'||g.kind==='group-resize'){const dx=p.x-g.p.x,dy=p.y-g.p.y;if(g.kind==='group-move'){g.group.x=g.start.x+dx;g.group.y=g.start.y+dy;for(const m of g.members){m.n.x=m.x+dx;m.n.y=m.y+dy;const el=ed.nodes.querySelector('[data-ne-node="'+m.n.id+'"]');el.style.left=m.n.x+'px';el.style.top=m.n.y+'px';}}else{g.group.w=Math.max(160,g.start.w+dx);g.group.h=Math.max(90,g.start.h+dy);}renderGroups(ed);renderWires(ed);return;}
 if(g.kind==='node'){g.node.x=g.start.x+p.x-g.p.x;g.node.y=g.start.y+p.y-g.p.y;const el=ed.nodes.querySelector('[data-ne-node="'+g.node.id+'"]');el.style.left=g.node.x+'px';el.style.top=g.node.y+'px';renderWires(ed);}
 if(g.kind==='pan'){ed.board.view.x=g.start.x+e.clientX-g.sx;ed.board.view.y=g.start.y+e.clientY-g.sy;transform(ed);}
 if(g.kind==='edge'&&g.segment!=null){g.edge.routeOffset=(g.startOffset||0)+p.x-g.p.x;delete g.edge.waypoints;renderWires(ed);}
});
document.addEventListener('pointerup',e=>{
 if(!gesture)return;const g=gesture;if(g.kind==='wire'){if(!g.moved&&!g.sticky){g.sticky=true;return;}finishWire(e);return;}gesture=null;
 if(g.kind==='group-draw'){g.ed.root.querySelector('.ne-group-draft').hidden=true;if(g.moved){const p=worldPoint(g.ed,e);g.ed.board.groups.push({id:'group-'+Date.now(),x:Math.min(p.x,g.p.x),y:Math.min(p.y,g.p.y),w:Math.max(160,Math.abs(p.x-g.p.x)),h:Math.max(90,Math.abs(p.y-g.p.y)),title:'새 그룹',color:'#799e91'});renderGroups(g.ed);}return;}
 if(g.kind==='pan'&&!g.moved&&!suppressClick&&!g.closeMenu)showAdd(g.ed,e);if(g.kind==='edge'&&!g.moved)selectEdge(g.ed,g.edge.id,e);
 if(g.kind==='node'||g.kind==='edge'&&g.moved)renderWires(g.ed);
});
document.addEventListener('pointercancel',e=>{if(gesture?.kind==='wire')finishWire(e,true);else gesture=null;});
document.addEventListener('pointerdown',e=>{if(!e.target.closest('.ne-menu,.ne-viewport'))menu.hidden=true;});
document.addEventListener('keydown',e=>{if(e.key==='Escape'){if(gesture?.kind==='wire')finishWire(e,true);gesture=null;Object.values(editors).forEach(ed=>{ed.groupDraw=false;ed.viewport.classList.remove('group-drawing');ed.root.querySelector('.ne-group-draft').hidden=true;});menu.hidden=true;deleteButton.hidden=true;}
 if(['Delete','x','X'].includes(e.key)&&!e.target.matches('input,textarea,select')){const ed=Object.values(editors).find(ed=>ed.root.contains(document.activeElement));if(ed?.board.selectedEdge){ed.board.removeEdge(ed.board.selectedEdge);deleteButton.hidden=true;render(ed);}}
});
document.addEventListener('workspace-render',()=>{menu.hidden=true;deleteButton.hidden=true;requestAnimationFrame(()=>Object.values(editors).forEach(ed=>renderWires(ed)));});
seed();buildEditor('production');buildEditor('planning');W.activate('production');requestAnimationFrame(()=>{fit(editors.production);fit(editors.planning);});
setInterval(()=>{if(state.paused)return;const ed=editors.planning;if(ed.board.tick(state.speed)){if(!ed.root.contains(document.activeElement)||!document.activeElement.matches('input,select,textarea'))render(ed);else for(const n of ed.board.nodes.filter(n=>n.type==='fleet')){const el=ed.nodes.querySelector('[data-ne-node="'+n.id+'"] .ne-metrics');if(el)el.innerHTML=metrics(n);}}},1000);
document.querySelector('.version b').textContent='05';
window.NodeEditors={boards,editors,fit:kind=>fit(editors[kind]),render:kind=>render(editors[kind]),add:(kind,type,x,y,sub)=>{const n=editors[kind].board.add(type,x,y,sub);render(editors[kind]);return n;},model:M};
log('노드 편집기 05 / 생산관리·계획은 해역과 분리된 시험 그래프입니다.','SYSTEM');
})();

// Independent planning documents. Runtime ship location is not operator/planning data.
(()=>{
const E=NodeEditors,M=E.model,ed=E.editors.planning,key='pelagic-planning-layers-v13';
let layers=[{id:'plan-1',name:'출정 계획 1',board:ed.board}],active='plan-1',sequence=1,lastSaved='',searchTarget=null;
const strip=document.createElement('div');strip.className='planning-layers';strip.setAttribute('aria-label','계획 레이어');ed.root.prepend(strip);
const picker=document.createElement('dialog');picker.id='coordinatePicker';document.body.append(picker);
const output=document.createElement('dialog');output.id='planFormat';document.body.append(output);
function snapshot(){return{version:1,active,sequence,layers:layers.map(l=>({id:l.id,name:l.name,board:{nodes:l.board.nodes,edges:l.board.edges,groups:l.board.groups,view:l.board.view,lineMode:l.board.lineMode}}))};}
function save(){const data=JSON.stringify(snapshot());if(data===lastSaved)return;try{localStorage.setItem(key,data);lastSaved=data;}catch{toast('계획 레이어를 저장하지 못했습니다.');}}
function decode(raw){if(!raw||!Array.isArray(raw.nodes)||raw.nodes.length>100||!Array.isArray(raw.edges)||raw.edges.length>400)throw Error('잘못된 레이어');const b=new M.Board('planning'),ids=new Map(),ports=new Map();for(const old of raw.nodes){if(!['coordinate','plan','fleet'].includes(old.type)||ids.has(old.id)||!Number.isFinite(old.x)||!Number.isFinite(old.y))throw Error('잘못된 노드');const n=M.createNode(old.type,old.x,old.y,old.subtype),id=n.id;Object.assign(n,old);n.id=id;n.location='[270,510]';n.status='대기중';n.travel=0;delete n.travelTarget;ids.set(old.id,id);for(const side of ['inputs','outputs']){if(!Array.isArray(old[side])||old[side].length>24)throw Error('잘못된 포트');n[side]=old[side].map(p=>{const fresh=M.createNode('coordinate',0,0).outputs[0];ports.set(p.id,fresh.id);return{id:fresh.id,kind:'plan',...(old.type==='coordinate'?{coordinate:p.coordinate??old.coordinate??'',siteId:p.siteId}:{})};});}b.nodes.push(n);}b.normalizePlanning();for(const e of raw.edges){if(b.node(ids.get(e.from))?.subtype==='exploration')continue;const r=b.connect(ids.get(e.from),ports.get(e.out),ids.get(e.to),ports.get(e.in),e.toSide);if(!r.ok)throw Error(r.error);}b.groups=(raw.groups||[]).filter(g=>['x','y','w','h'].every(k=>Number.isFinite(g[k])));if(raw.view&&['x','y','scale'].every(k=>Number.isFinite(raw.view[k])))b.view={...raw.view,scale:Math.max(.25,Math.min(1.8,raw.view.scale))};b.lineMode=raw.lineMode==='straight'?'straight':'curve';b.recompute();return b;}
try{const data=JSON.parse(localStorage.getItem(key)||'null');if(data?.version===1&&Array.isArray(data.layers)&&data.layers.length&&data.layers.length<=30){if(data.layers.some(l=>l.board?.nodes?.some(n=>n.type==='coordinate'&&n.inputs?.length))&&!localStorage.getItem(key+'-before-v19'))localStorage.setItem(key+'-before-v19',JSON.stringify(data));const restored=data.layers.map(l=>({id:String(l.id),name:String(l.name).slice(0,50),board:decode(l.board)}));layers=restored;active=layers.some(l=>l.id===data.active)?data.active:layers[0].id;sequence=Math.max(data.sequence||1,layers.length);}}catch{toast('계획 레이어 복원 실패 · 기존 기본 계획을 유지합니다.');}
function tabs(){strip.innerHTML=layers.map(l=>'<span class="planning-layer-tab" role="tab" tabindex="0" aria-selected="'+(l.id===active)+'" data-plan-layer="'+esc(l.id)+'" title="클릭: 계획 레이어 전환"><button aria-label="레이어 이름 편집" data-layer-edit="'+esc(l.id)+'">✎</button><span data-layer-name="'+esc(l.id)+'">'+esc(l.name)+'</span> <small>'+l.board.nodes.length+' nodes</small> <span role="button" tabindex="0" aria-label="레이어 삭제" data-layer-delete="'+esc(l.id)+'">×</span></span>').join('')+'<button data-plan-new aria-label="계획 레이어 추가">＋ 새 레이어</button>';}
function activate(id){const l=layers.find(v=>v.id===id);if(!l)return;const old=layers.find(v=>v.id===active);if(old)old.board=ed.board;active=id;ed.board=l.board;E.boards.planning=l.board;E.render('planning');tabs();save();}
strip.addEventListener('click',e=>{e.stopPropagation();const del=e.target.closest('[data-layer-delete]')?.dataset.layerDelete;if(del){const l=layers.find(l=>l.id===del);if(!confirm(l.name+' 레이어와 모든 내용을 삭제할까요?'))return;layers=layers.filter(l=>l.id!==del);if(!layers.length){const id='plan-'+(++sequence);layers.push({id,name:'출정 계획 '+sequence,board:new M.Board('planning')});}if(active===del){active=layers[0].id;ed.board=layers[0].board;E.boards.planning=ed.board;E.render('planning');}tabs();save();return;}if(e.target.closest('[data-layer-input]'))return;const rename=e.target.closest('[data-layer-edit]')?.dataset.layerEdit;if(rename){editName(rename);return;}if(e.target.closest('[data-plan-new]')){const id='plan-'+(++sequence);layers.push({id,name:'출정 계획 '+sequence,board:new M.Board('planning')});activate(id);}const id=e.target.closest('[data-plan-layer]')?.dataset.planLayer;if(id)activate(id);});
strip.addEventListener('keydown',e=>{if(e.target.matches('[data-layer-delete],[data-plan-layer]')&&['Enter',' '].includes(e.key)){e.preventDefault();e.target.click();}});
function editName(id){const l=layers.find(v=>v.id===id),label=strip.querySelector('[data-layer-name="'+id+'"]');if(!l||!label)return;const input=document.createElement('input');input.dataset.layerInput=id;input.value=l.name;input.maxLength=50;input.setAttribute('aria-label','레이어 이름');label.replaceWith(input);let done=false;function finish(cancel=false){if(done)return;done=true;if(!cancel&&input.value.trim())l.name=input.value.trim();tabs();save();}input.addEventListener('blur',()=>finish());input.addEventListener('keydown',e=>{e.stopPropagation();if(e.key==='Enter'||e.key==='Escape'){e.preventDefault();finish(e.key==='Escape');}});input.focus();input.select();}

function candidates(){return [...nodes.map(n=>({id:n.id,name:n.name,x:n.x,y:n.y,type:n.purity?'자원':'거점'})),{id:'contact-07',name:'미확인 위협 / CONTACT',x:840,y:195,type:'위협 · 예시 접촉'}];}
function results(){const q=picker.querySelector('input').value.trim().toLowerCase();picker.querySelector('.coordinate-results').innerHTML=candidates().filter(n=>(n.name+n.type+'['+n.x+','+n.y+']').toLowerCase().includes(q)).map(n=>'<button data-pick-coordinate="'+esc(n.id)+'"><strong>'+esc(n.name)+'</strong><span>'+esc(n.type)+' · ['+n.x+','+n.y+']</span></button>').join('')||'<p>일치하는 좌표가 없습니다.</p>';}
function search(board,n,portId){searchTarget={board,id:n.id,portId:portId||n.outputs[0]?.id};picker.innerHTML='<form method="dialog"><h2>해역 좌표 검색</h2><button class="dialog-close" value="close" aria-label="닫기">×</button></form><input aria-label="거점 또는 위협 검색" placeholder="거점 이름, 자원, 위협 또는 좌표 검색"><div class="coordinate-results"></div><small>현재 해역 거점과 지도에 표시된 예시 위협을 조회합니다.</small>';picker.querySelector('input').addEventListener('input',results);results();picker.showModal();picker.querySelector('input').focus();}
picker.addEventListener('click',e=>{const id=e.target.closest('[data-pick-coordinate]')?.dataset.pickCoordinate;if(!id)return;const c=candidates().find(n=>n.id===id),n=searchTarget?.board.node(searchTarget.id);if(c&&n){const port=n.outputs.find(p=>p.id===searchTarget.portId);if(!port)return;port.coordinate='['+c.x+','+c.y+']';port.siteId=c.id;searchTarget.board.recompute();if(searchTarget.board===ed.board)E.render('planning');save();}picker.close();});
function compile(board,n){board.recompute();const route=(n.coordinateBindings||[]).filter(v=>v.destination).map(v=>({nodeId:v.nodeId,portId:v.portId,coordinate:v.coordinate}));if(!route.length||route.some(r=>!/^\[\d{1,4},\d{1,4}\]$/.test(r.coordinate)||r.coordinate.slice(1,-1).split(',').some((v,i)=>Number(v)>(i?1520:2000)))){toast('출력에 목적지 좌표를 연결하세요.');return;}const origins=[],seen=new Set();function upstream(id){if(seen.has(id))return;seen.add(id);for(const e of board.edges.filter(e=>e.to===id&&!e.error)){const source=board.node(e.from);if(e.toSide==='outputs')continue;if(source?.type==='coordinate'){const p=source.outputs.find(p=>p.id===e.out);if(p?.coordinate)origins.push(p.coordinate);}upstream(e.from);}}upstream(n.id);const format={schemaVersion:1,kind:'fleet_movement_plan',layerId:active,templateId:n.id,title:n.title,originCoordinates:origins,route,ships:n.ships.map(r=>({type:r.type,requested:r.count})),autoFill:!!n.autoFill,status:'draft'};const json=JSON.stringify(format,null,2);try{localStorage.setItem('pelagic-command-format-v13',json);}catch{toast('양식 저장 실패 · JSON을 복사해 보관하세요.');}output.innerHTML='<form method="dialog"><h2>출정 명령 양식</h2><button class="dialog-close" value="close" aria-label="닫기">×</button></form><p>DB 전달용 초안 · 생성만으로 함대가 이동하지 않습니다.</p><textarea readonly aria-label="명령 JSON"></textarea><button data-format-download>JSON 다운로드</button>';output.querySelector('textarea').value=json;output.querySelector('[data-format-download]').onclick=()=>{const url=URL.createObjectURL(new Blob([json],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='fleet-plan.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};output.showModal();return format;}
// Save/load toolbar commands apply only to the open layer; the collection is autosaved separately.
ed.root.addEventListener('click',()=>{const l=layers.find(v=>v.id===active);if(l)l.board=ed.board;tabs();save();});
setInterval(()=>{const l=layers.find(v=>v.id===active);if(l)l.board=ed.board;save();},1000);
window.PlanningUI={search,compile,activate,save,get layers(){return layers;},get active(){return active;}};
// Do not replace the restored board with the initial board when opening the first document.
ed.board=layers.find(l=>l.id===active).board;E.boards.planning=ed.board;E.render('planning');tabs();
})();
