'use strict';
(()=>{
const W=window.Workspace, svgNS='http://www.w3.org/2000/svg';let links=[],activeLink=null,wire=null,mapDrag=null,graphDrag=null;
const positions={iron:{x:75,y:115},copper:{x:75,y:360},refinery:{x:440,y:200},base:{x:800,y:245},gas:{x:440,y:465},quartz:{x:75,y:545}};
const graphView={x:0,y:0,w:1120,h:700};let menuNode=null;
const menu=document.createElement('div');menu.id='nodeActions';menu.className='node-actions';menu.hidden=true;document.body.append(menu);
const production=W.ensurePane('production');production.innerHTML='<div class="graphpane"><div class="graphbar"><b>생산 네트워크</b><span>출력 ● → 입력 ● 드래그로 정기항로 연결</span><button id="removeLink">선택 연결 삭제</button><button id="graphReset">시점 복원</button><span class="badge">연결 명령 데모</span></div><svg id="productionGraph" class="graphcanvas" viewBox="0 0 1120 700" aria-label="생산 노드 편집기"><defs><pattern id="productionDots" width="22" height="22" patternUnits="userSpaceOnUse"><circle cx="1" cy="1" r=".7" fill="#496361"/></pattern></defs><rect x="-5000" y="-5000" width="10000" height="10000" fill="#14252b"/><rect x="-5000" y="-5000" width="10000" height="10000" fill="url(#productionDots)"/><g id="graphWires"></g><g id="graphNodes"></g><path id="graphGhost" class="wire-ghost" hidden/></svg><div class="graph-tip">노드 제목을 드래그해 배치 · 빈 공간 드래그로 이동 · 휠 확대 · 연결선 클릭 후 Delete로 삭제</div></div>';
const research=W.ensurePane('research');research.innerHTML='<div class="feature-page"><div class="featuretop"><div><span class="eyebrow">RESEARCH / 기술 계획</span><h1>연구 관리</h1></div><span class="badge">연구 실행은 후속 MVP</span></div><p>각 연구의 요구 자원과 선행 조건을 검토하고 계획 대상으로 표시합니다.</p><div class="feature-grid">'+[['REF-01','회수율 개선','철재 120 · 구리 40','기초 정제'],['CORE-02','연산코어 증설','전장품 24 · 금 4','레이더 해금'],['BAT-02','고밀도 배터리','축전 소재 80 · 구리 60','현지 전력'],['HULL-03','순양함 설계','구조재 400 · 전장품 30','군수 설비']].map(r=>'<article class="feature-card"><span class="badge">'+r[0]+'</span><h3>'+r[1]+'</h3><div class="stat">필요 자원</div><p>'+r[2]+'</p><div class="stat">선행 <b>'+r[3]+'</b></div><button class="featurebutton" data-plan="'+r[1]+'">계획 표시</button></article>').join('')+'</div></div>';
const trade=W.ensurePane('trade');trade.innerHTML='<div class="feature-page"><div class="featuretop"><div><span class="eyebrow">EXCHANGE / 외부 통신</span><h1>무역 관리</h1></div><span class="badge">시세·계약 예시</span></div><p>교환 조건과 운송 여력을 검토합니다. 실제 거래·자원 지출은 아직 연결되지 않았습니다.</p><div class="feature-grid">'+[['금 교환','구조재 200 → 금 4','24 화물 · 1회 왕복'],['축전 소재 확보','구리 120 → 축전 소재 60','60 화물 · 냉각 불필요'],['생활보급품','철재 80 → 보급품 20','20 화물 · 우선 운송']].map(r=>'<article class="feature-card"><span class="badge">OFFER / OPEN</span><h3>'+r[0]+'</h3><p>'+r[1]+'</p><div class="stat">'+r[2]+'</div><button class="featurebutton" data-trade="'+r[0]+'">검토 표시</button></article>').join('')+'</div><h2>배정 운송 수단</h2>'+table(['함대','적재량','상태'],[['LOGISTICS-02','수송선 × 2','항로 지정 가능']])+'</div>';
function at(id){let n=nodes.find(n=>n.id===id);return positions[id]||{x:n.x,y:n.y};}
function curve(a,b){const dx=Math.max(65,Math.abs(b.x-a.x)*.5);return 'M'+a.x+','+a.y+' C'+(a.x+dx)+','+a.y+' '+(b.x-dx)+','+b.y+' '+b.x+','+b.y;}
function sceneCurve(a,b){const dx=(b.x-a.x)*.35;return 'M'+a.x+','+a.y+' C'+(a.x+dx)+','+(a.y-50)+' '+(b.x-dx)+','+(b.y-50)+' '+b.x+','+b.y;}
function validLinks(){links=links.filter(l=>nodes.some(n=>n.id===l.from)&&nodes.some(n=>n.id===l.to)&&state.orders.some(o=>String(o.id)===String(l.order)));}
function renderLinks(){validLinks();const wires=production.querySelector('#graphWires');if(wires)wires.innerHTML=links.map(l=>{let a=at(l.from),b=at(l.to);return '<path class="link-wire '+(activeLink===l.order?'selected':'')+'" data-link="'+l.order+'" d="'+curve({x:a.x+210,y:a.y+93},{x:b.x,y:b.y+93})+'"/>';}).join('');
$$('#routeLayer .node-connection').forEach(e=>e.remove());links.forEach(l=>{let a=nodes.find(n=>n.id===l.from),b=nodes.find(n=>n.id===l.to),p=document.createElementNS(svgNS,'path');p.setAttribute('d',sceneCurve({x:a.x+17,y:a.y+26},{x:b.x-17,y:b.y+26}));p.setAttribute('class','link-wire node-connection');p.dataset.link=l.order;p.dataset.order=l.order;$('#routeLayer').append(p);});}
function renderGraph(){if(production.dataset.customEditor){renderLinks();return;}production.querySelector('#graphNodes').innerHTML=nodes.map(n=>{let p=at(n.id);return '<g class="graph-node '+(n.id===state.selected?'selected':'')+'" data-graph-node="'+n.id+'" transform="translate('+p.x+' '+p.y+')"><rect class="cardface" width="210" height="146" rx="3"/><rect width="210" height="32" fill="#30474a"/><text class="graph-title" x="13" y="22">'+esc(n.name)+'</text><text class="graph-label" x="13" y="57">'+esc(n.purity?'순도 '+n.purity+'% / '+n.rate+' per min':n.type)+'</text><text class="graph-label" x="13" y="75">재고 '+esc(n.stock)+'</text><text class="graph-label" x="14" y="113">입력</text><text class="graph-label" x="167" y="113">출력</text><text class="graph-label" x="13" y="134">'+esc(n.power)+'</text><circle class="port" data-port="in" data-port-node="'+n.id+'" cx="0" cy="93" r="7"/><circle class="port" data-port="out" data-port-node="'+n.id+'" cx="210" cy="93" r="7"/></g>';}).join('');renderLinks();}
const oldNodes=renderNodes;renderNodes=function(){oldNodes();$$('.mapnode').forEach(g=>{const id=g.dataset.id;[['in',-17],['out',17]].forEach(([kind,x])=>{let c=document.createElementNS(svgNS,'circle');c.setAttribute('class','port');c.setAttribute('cx',x);c.setAttribute('cy',26);c.setAttribute('r','5.5');c.dataset.port=kind;c.dataset.portNode=id;g.append(c);});});renderGraph();};
const oldInspector=renderInspector;renderInspector=function(){oldInspector();const el=document.createElement('div');el.className='node-command-list';el.innerHTML=[['inspect','상태 조회'],['scan','탐사 시작'],['route','항로 시작'],['attack','공격 출정'],['defend','방어 배치'],['mine','채굴 출정'],['build','시설 계획'],['return','회수 귀환']].map(([k,t])=>'<button data-node-action="'+k+'" data-target="'+state.selected+'">'+t+'</button>').join('');$('#inspectorBody .inspectcontent').append(el);};
function showMenu(id,x,y){menuNode=id;const n=nodes.find(n=>n.id===id);menu.innerHTML='<div class="nodeheading">'+esc(n.name)+'</div>'+[['inspect','상태 조회'],['scan','탐사 시작'],['route','연결 시작'],['attack','공격 출정'],['defend','방어선 구축'],['mine','채굴선 출정'],['build','시설 계획'],['return','회수·귀환']].map(([a,t])=>'<button data-node-action="'+a+'" data-target="'+id+'">'+t+'<small>↵</small></button>').join('');menu.style.left=Math.max(5,Math.min(innerWidth-225,x+12))+'px';menu.style.top=Math.max(60,Math.min(innerHeight-325,y+10))+'px';menu.hidden=false;}
function startScan(p){if(state.scan){toast('탐사가 이미 진행 중입니다.');return false;}if(state.orders.length>=4){toast('사용 가능한 연산코어가 없습니다.');return false;}state.scan={x:Math.max(30,Math.min(1970,p.x)),y:Math.max(30,Math.min(1490,p.y)),progress:0};renderOrders();log('탐사 지정 ['+Math.round(p.x)+','+Math.round(p.y)+'] / SURVEY-01','SCAN');return true;}
function connect(from,to){if(from===to){toast('같은 노드에는 연결할 수 없습니다.');return false;}if(links.some(l=>l.from===from&&l.to===to)){toast('이미 같은 방향의 연결이 있습니다.');return false;}if(!nodes.some(n=>n.id===from)||!nodes.some(n=>n.id===to))return false;const a=nodes.find(n=>n.id===from),b=nodes.find(n=>n.id===to);if(!addOrder('연결 '+a.name+' → '+b.name))return false;links.push({from,to,order:state.orders.at(-1).id});renderLinks();state.quest.route=true;updateQuests();log('정기항로 연결: '+a.name+' → '+b.name+' / 운송 시뮬레이션은 준비 중','ROUTE');toast('노드 연결 등록 · 코어 1 사용');return true;}
function removeLink(){if(activeLink==null){toast('삭제할 연결선을 먼저 선택하세요.');return;}state.orders=state.orders.filter(o=>o.id!==activeLink);activeLink=null;renderOrders();renderLinks();log('연결 종료 / 코어 반환','ROUTE');}
function nearest(p,max=35){return nodes.find(n=>Math.hypot(n.x-p.x,n.y-p.y)<=max);}
function nodeAction(action,id){const n=nodes.find(n=>n.id===id);if(!n)return false;select(id);menu.hidden=true;if(action==='inspect'){W.activate('inspector');return true;}if(action==='scan')return startScan(n);if(action==='route'){state.draft=[id];setTool('route');renderDraft();toast('다음 노드를 클릭하거나 출력 연결점에서 입력점으로 드래그하세요.');return true;}if(action==='build'){setTool('build');W.activate('inspector');return true;}const names={attack:'공격 진출',defend:'방어선 구축',mine:'채굴선 출정',return:'회수·귀환'};if(names[action]){if(!addOrder(names[action]+' / '+n.name))return false;log(names[action]+' 명령 등록 / 실제 이동·전투는 미구현','ORDER');toast('작전 명령 등록');return true;}return false;}
const map=$('#map').cloneNode(true);$('#map').replaceWith(map);
function localPoint(svg,e){let p=svg.createSVGPoint();p.x=e.clientX;p.y=e.clientY;return p.matrixTransform(svg.getScreenCTM().inverse());}
function beginWire(e,svg){const port=e.target.closest('[data-port]');if(!port)return false;if(port.dataset.port!=='out'){toast('출력 연결점에서 입력 연결점으로 드래그하세요.');return true;}wire={from:port.dataset.portNode,svg};menu.hidden=true;e.preventDefault();return true;}
map.addEventListener('pointerdown',e=>{if(e.button!==0)return;if(beginWire(e,map))return;let p=localPoint(map,e);mapDrag={p,x:e.clientX,y:e.clientY,view:{...state.view},target:e.target.closest('[data-id]')?.dataset.id,moved:false};menu.hidden=true;map.setPointerCapture(e.pointerId);});
map.addEventListener('pointermove',e=>{let p=localPoint(map,e);$('#coordinates').textContent='X '+Math.round(p.x)+' · Y '+Math.round(p.y);if(!mapDrag)return;const g=mapDrag;g.moved=g.moved||Math.hypot(e.clientX-g.x,e.clientY-g.y)>5;
if(state.tool==='scan'){let r=$('#selectionRect');for(const [k,v]of Object.entries({x:Math.min(g.p.x,p.x),y:Math.min(g.p.y,p.y),width:Math.abs(p.x-g.p.x),height:Math.abs(p.y-g.p.y)}))r.setAttribute(k,v);r.setAttribute('visibility','visible');}
else if(!g.target||state.tool==='pan'){const v=g.view;state.view.x=v.x-(p.x-g.p.x);state.view.y=v.y-(p.y-g.p.y);view();g.p=localPoint(map,e);g.view={...state.view};}});
map.addEventListener('pointerup',e=>{if(!mapDrag)return;const g=mapDrag;mapDrag=null;$('#selectionRect').setAttribute('visibility','hidden');if(state.tool==='scan'){if(!g.moved){toast('영역을 드래그하거나 노드 명령에서 탐사를 시작하세요.');return;}let p=localPoint(map,e);startScan({x:(g.p.x+p.x)/2,y:(g.p.y+p.y)/2});return;}if(g.target&&!g.moved){if(state.tool==='route'&&state.draft.length){const from=state.draft.at(-1);if(connect(from,g.target)){state.draft=[];renderDraft();}}else if(state.tool==='route'){state.draft=[g.target];renderDraft();}select(g.target);if(state.tool!=='route')showMenu(g.target,e.clientX,e.clientY);}});
map.addEventListener('pointercancel',()=>{mapDrag=null;$('#selectionRect').setAttribute('visibility','hidden');});
map.addEventListener('wheel',e=>{e.preventDefault();const p=localPoint(map,e),v=state.view,w=Math.max(400,Math.min(1800,v.w*(e.deltaY>0?1.1:.9))),r=w/v.w;state.view={x:p.x-(p.x-v.x)*r,y:p.y-(p.y-v.y)*r,w,h:v.h*r};view();},{passive:false});
const gsvg=production.querySelector('#productionGraph');
gsvg.addEventListener('pointerdown',e=>{if(e.button!==0)return;if(beginWire(e,gsvg))return;const link=e.target.closest('[data-link]');if(link){activeLink=Number(link.dataset.link);renderLinks();return;}const target=e.target.closest('[data-graph-node]');let p=localPoint(gsvg,e);graphDrag={id:target?.dataset.graphNode,p,x:e.clientX,y:e.clientY,start:target?{...at(target.dataset.graphNode)}:{...graphView},moved:false};menu.hidden=true;gsvg.setPointerCapture(e.pointerId);});
gsvg.addEventListener('pointermove',e=>{if(!graphDrag)return;const g=graphDrag,p=localPoint(gsvg,e);g.moved=g.moved||Math.hypot(e.clientX-g.x,e.clientY-g.y)>5;if(g.id){positions[g.id]={x:g.start.x+p.x-g.p.x,y:g.start.y+p.y-g.p.y};renderGraph();}else{graphView.x=g.start.x-(p.x-g.p.x);graphView.y=g.start.y-(p.y-g.p.y);gsvg.setAttribute('viewBox',[graphView.x,graphView.y,graphView.w,graphView.h].join(' '));g.p=localPoint(gsvg,e);g.start={...graphView};}});
gsvg.addEventListener('pointerup',e=>{if(!graphDrag)return;const g=graphDrag;graphDrag=null;if(g.id){select(g.id);renderGraph();if(!g.moved)showMenu(g.id,e.clientX,e.clientY);}});
gsvg.addEventListener('wheel',e=>{e.preventDefault();let p=localPoint(gsvg,e),w=Math.max(600,Math.min(2200,graphView.w*(e.deltaY>0?1.1:.9))),r=w/graphView.w;Object.assign(graphView,{x:p.x-(p.x-graphView.x)*r,y:p.y-(p.y-graphView.y)*r,w,h:graphView.h*r});gsvg.setAttribute('viewBox',[graphView.x,graphView.y,graphView.w,graphView.h].join(' '));},{passive:false});
function clearWire(){wire=null;$('#mapGhost')?.remove();production.querySelector('#graphGhost')?.setAttribute('hidden','');}
document.addEventListener('pointermove',e=>{if(!wire)return;const p=localPoint(wire.svg,e);if(wire.svg===map){let path=$('#mapGhost');if(!path){path=document.createElementNS(svgNS,'path');path.id='mapGhost';path.setAttribute('class','wire-ghost');$('#routeLayer').append(path);}const n=nodes.find(n=>n.id===wire.from);path.setAttribute('d',sceneCurve({x:n.x+17,y:n.y+26},p));}else{let a=at(wire.from),path=production.querySelector('#graphGhost');path.hidden=false;path.removeAttribute('hidden');path.setAttribute('d',curve({x:a.x+210,y:a.y+93},p));}});
document.addEventListener('pointerup',e=>{if(!wire)return;const port=document.elementFromPoint(e.clientX,e.clientY)?.closest('[data-port]');if(port?.dataset.port==='in')connect(wire.from,port.dataset.portNode);else toast('대상 노드의 입력 연결점에 놓으세요.');clearWire();});
document.addEventListener('pointercancel',()=>{clearWire();graphDrag=null;});
document.addEventListener('click',e=>{const a=e.target.closest('[data-node-action]');if(a){nodeAction(a.dataset.nodeAction,a.dataset.target);return;}const plan=e.target.closest('[data-plan], [data-trade]');if(plan){plan.closest('.feature-card').classList.toggle('active');plan.textContent=plan.closest('.feature-card').classList.contains('active')?'표시 해제':'계획 표시';log('검토 대상 변경: '+(plan.dataset.plan||plan.dataset.trade),'PLAN');}if(e.target.id==='removeLink')removeLink();if(e.target.id==='graphReset'){Object.assign(graphView,{x:0,y:0,w:1120,h:700});gsvg.setAttribute('viewBox','0 0 1120 700');}if(e.target.closest('[data-cancel]'))renderLinks();if(!e.target.closest('.node-actions,.mapnode,.graph-node')&&!e.target.closest('[data-node]'))menu.hidden=true;});
document.addEventListener('keydown',e=>{if(e.key==='Escape'){menu.hidden=true;clearWire();graphDrag=null;}if(e.key==='Delete'&&!e.target.matches('input,textarea')&&gsvg.getBoundingClientRect().width){removeLink();}});
document.addEventListener('workspace-render',()=>{menu.hidden=true;renderGraph();});
const oldCommit=commitRoute;commitRoute=function(){oldCommit();renderGraph();};
window.Operations={nodeAction,startScan,connect,nearest,renderGraph,getLinks:()=>links,removeLink};
renderNodes();renderInspector();W.render();
})();
